# **프로그래밍 기초 개념**

## **0. Before We Start**

### **0.1. Hello to New Quants! 🖐️**

- 안녕하세요, 학회원 여러분! 드디어 본격적으로 공통과정을 시작하게 됩니다!
- 여러분은 오늘 1주차를 시작으로, 앞으로 16주차까지 퀀트를 위한 기초적인 이론을 학습하고 실습을 하게 됩니다.
- 전체세션에서 활동 방법에 대해 설명을 들었겠지만, 다시 한 번 간략하게 설명드리자면,
    1. 매주 `.ipynb` 형식의 **노트의 내용을 학습하면서 개념을 익히고**, 해당 개념을 바탕으로 **과제를 해결**하시면 됩니다.
    2. 팀 세션에서는 해결한 과제를 팀원과 공유하면서 다양한 방식의 접근법에 대해 토론하시면 됩니다.
    3. 전체 세션은 앞으로 활동하는 기간 동안 월 1회 진행되며 (학회 운영 방향에 따라 달라질 수 있습니다.) 팀 세션과 별도로 진행됩니다. (미정: 전체 세션에서는 미니 프로젝트가 주어지며, 학회원분들은 팀원과 협력하여 프로젝트를 시간 내에 완성하시면 됩니다.)
- 우수 팀에게는 혜택이 있으니 다음 전체 세션까지 다들 화이팅하시길 바랍니다!

### **0.2. About the First Part of the Curriculum**

- 첫번째 학습주제는 **파이썬 프로그래밍**입니다.
- 앞으로 3주간 신입 학회원분들께서는 **파이썬**을 이용하여 **프로그래밍의 기초 개념**을 학습하고, 기초적인 **선형대수학**과 **통계학**의 내용을 파이썬으로 구현하는 방법에 대해 배울 예정입니다.
- 1주차에 해당하는 이번주는 파이썬을 이용한 프로그래밍의 기초 개념을 학습합니다.
- 처음이라고 해서 봐주지 않습니다!😀 절대 적은 내용이 아니지만 4주차부터 배울 방법론을 구현하기 위해서는 첫 3주동안 기본이 되는 내용은 모두 학습하셔야 합니다.
- 그런 의미에서 첫 3주가 가장 고통스러운 기간이니 버텨주시길 바랍니다.😥
- 준비되셨나요? 그럼 이제 시작하겠습니다!

---

- `(코드)` : 코드 내용을 설명할 떄 음영처리를 합니다.
- **[Exercise]** : 직접 풀어보는 문제입니다. 해설이 제공되지 않으므로 팀원과 의견을 공유해보시길 바랍니다!

## **1. Basic Programming Concepts**

- 1절에서는 파이썬을 이용하여 프로그래밍의 기본개념과 앞으로 모르는 것이 있을 때 도움을 받을 수 있는 방법에 대하여 알아보겠습니다.
- **`1.5`**와 **`1.6`**은 처음 보면 어떤 말인지 헷갈릴 수 있는데, 앞으로 하다보면 익숙해지기도 하고 8절에서 그 개념에 대해 다루니 모르시겠더라도 넘어가면 됩니다.

### **1.1. Variable Assignment**

- 가장 먼저, **변수 할당(variable assignment)**에 대하여 알아봅시다.
    - 공학적 원리를 자세히 이해하기보다는 활용하는 측면에서 가볍게 알아보겠습니다.

#### 1.1.1. Variables and Assignment

- 프로그래밍할 때 **변수(variable)에 정보를 저장**할 수 있으면 유용합니다.
- 아래에는 변수 `x`에 "Hello World"라는 값을 할당해보겠습니다.
    - 아래처럼 셀(혹은 프롬프트)에 코드를 쓰고 `shift + enter`을 눌러 실행하면 됩니다.

In [ ]:
x = "Hello World"

- 변수에 값을 할당하면 파이썬에서는 현재 세션이 계속 실행되는 한 이 변수를 기억합니다.
    - 예를 들어 현재 강의자료를 닫지 않는한 위에서 실행한 `x`의 값을 언제든 불러올 수 있습니다.
- `x`를 불러와 그 값을 출력해보기 위해 아래 프롬프트에 `x`를 쓰고 셀을 실행하면 'Hello World'라는 값이 출력됩니다.

In [ ]:
x

'Hello World'

- 그러나 파이썬은 **아직 생성되지 않은 변수에 대해 요청하면 오류를 반환**합니다.
- 아래처럼 코드 셀에 `y`를 입력하고 실행하게 되면 아직 생성되지 않은 변수이기때문에 오류가 발생하여 에러 메시지를 보입니다.

In [ ]:
y

NameError: ignored

- 작업이 발생하는 순서를 이해하는 것도 중요합니다.
    1. 우변(등호 기호의 오른편)에 작성된 코드가 먼저 연산됩니다.
    2. 그러면 `1`에서 계산된 값이 등호 왼쪽의 변수로 저장됩니다.
- 즉 파이썬에서 등호 하나의 의미는 수학에서처럼 **좌변과 우변이 같다는 것이 아닌** **우변의 값이 좌변의 변수에 ‘담긴다’**라고 생각하면 편합니다.
- 변수는 메모리에 저장된 것에 이름을 바인딩(binding)합니다.
    - 각 이름은 **서로 다른 자료형의 값에 바인딩될 수도 있습니다.**
- 아직 배우진 않았지만, 아래를 보게 되면 `x`는 정수형 자료인 2에 바인딩되기도 하고 문자열 자료인 “something else”에 바인딩되기도 합니다.
- 실행해보면 알겠지만 변수 이름 하나에는 한 번에 하나의 값만 바인딩하게 됩니다. 따라서 처음에는 2에 바인딩되었다가 “something else”가 `x` 에 할당된 후 “something else”에 바인딩하게 됩니다.

In [ ]:
x = 2
print(x)
x = "something else"
print(x)

2
something else

#### 1.1.2. Variable Names

- 변수가 취할 수 있는 이름에는 몇 가지 규칙이 있습니다.
    - 변수는 **알파벳과 숫자, 그리고 밑줄(underscore) `_`만 포함**할 수 있습니다.
        - 한글도 가능하지만 영어 알파벳을 이용하는 것이 점차 편해집니다.
    - 단, **변수명의 첫 문자는 문자 또는 밑줄**이어야 합니다. 즉 숫자로 시작해서는 안됩니다.
    - 변수 이름 내 **공백은 허용되지 않습니다.** 공백이 필요하다면 대신 밑줄을 이용합니다.
    - 변수 이름은 **대소문자를 구분**합니다(예: `x`와 `X`는 서로 다른 변수로 간주됨).
- 순수 수학과 달리 프로그래밍의 변수는 거의 항상 유형(tangible; 有形)의 것을 나타냅니다.
    - 예를 들어, 공간의 두 지점 사이의 거리 또는 토끼의 개체 수를 나타낼 수 있습니다.
- 따라서 코드가 점점 더 복잡해짐에 따라 **변수가 나타내는 것과 쉽게 연관될 수 있는 이름을 갖는 것**이 매우 중요합니다.
    - 예를 들어, 공간의 두 지점 사이의 거리는 `x`라는 이름보다는 `dist` 변수로 더 잘 표현되고, 토끼 수는 `y`보다는 `nRabbits`로 표현하는 것이 코드를 읽었을 때 직관적으로 더 와닿을 것입니다.

#### 1.1.3. List of Variables

- 현재 세션에서 메모리에 저장된 모든 변수가 무엇인지 알고싶다면 셀에 매직 커맨드 `%whos`를 입력하고 실행합니다.

In [ ]:
%whos

Variable   Type    Data/Info
----------------------------
x          str     something else

- 변수 `x`에 가장 마지막에 할당한 값이 “something else”이므로 마지막 열에 something else가 적혀있는 것을 확인할 수 있습니다.
    - 여기서는 쌍따옴표가 없을 알 수 있습니다. 이유는 나중에 문자열에 대하여 배울 때 알 수 있습니다.
- `del` 함수를 사용하여 (주피터)노트북에서 변수를 지울 수 있습니다.
- `del x`를 입력하면 작업 공간에서 변수 `x`가 지워집니다.
- 노트북의 모든 변수를 제거하려면 매직커맨드인  `%reset`를 사용할 수 있습니다.

### **1.2. Code Comments**

- **주석(comment)**은 **자신과 코드를 읽는 다른 사람을 위해 남기는 짧은 메모**입니다.
- 주석은 코드의 기능을 설명하는 데 사용해야 합니다.
- **주석은 `#` 뒤에 작성**합니다. 파이썬은 `#` 가 있는 줄의 **`#` 뒤에 오는 모든 코드를 무시하고 다음 줄로 건너뜁니다**.
- 주석을 작성하는 연습을 해볼까요?

In [ ]:
i = 1 # 변수 i에 값 1을 할당한다.
j = 2 # 변수 j에 값 2를 할당한다.

# i에 j를 더한다.
i + j

3

- 위의 코드를 보면 파이썬이 `#` 뒤의 내용은 실행하지 않고 무시하였음을 알 수 있습니다.
- 나중에 더 자세히 언급하겠지만, 해당 코드를 실행하게 되면 계산기 처럼 1에 2가 더해진 3이 결과값으로 출력됩니다.

### **1.3. Built-in Functions**

- 함수는 입력(또는 입력들)을 받아 출력을 생성하는 과정을 말합니다.
- 두 개의 인수 `x`와 `y`를 취하는 `f`라는 함수가 있다면 함수를 사용하기 위해서는 `f(x, y)`를 작성합니다.
- 예를 들어 `print` 함수는 단순히 주어진 모든 것을 출력하는 기능을 가지고 있습니다.
- 이전에 생성한 `x`라는 변수를 떠올려 보세요. `print(x)`는 `x`의 값인 ‘something else’을 출력할 것입니다.

In [ ]:
print(x)

something else

- 이처럼 별도의 정의 과정 없이 파이썬 자체에 내장된 함수를 **내장함수(built-in function)**라고 합니다.
- `print` 외에도 여러 내장함수가 있지만 한 번에 외우기보단 나올 때마다 그때그때 익히는 것이 효율적입니다.

### **1.4. Getting Help**

- 아직은 모르는 함수가 너무 많습니다. 이때 우리는 도움을 요청함으로써 어떤 함수의 기능이 무엇인지 알아낼 수 있습니다.
- 주피터 노트북에서는 함수명 뒤에 `?`을 붙임으로써 함수의 기능을 확인할 수 있습니다.
- 예를 들어 앞서 확인했던 `print` 함수에 대한 설명을 확인하려면 셀에 `print?`를 입력하고 실행하면 됩니다.

In [ ]:
print?

- 주피터 노트북 파일을 실행한 방법에 따라 :
    - 주피터랩(JupyterLab): 셀 아래 텍스트에 도움말을 표시합니다.
    - 기존 주피터 노트북: 화면 하단에 새 패널을 표시합니다. Esc 키를 누르거나 패널 오른쪽 상단의 ‘x'를 클릭하여 이 패널을 종료할 수 있습니다.
    - 구글 코랩: 우측 상단에 새 패널을 표시합니다.
- 앞으로 함수를 직접 정의하는 방법을 포함하여 함수에 대해 더 많이 배울 것입니다.

### **1.5. Objects and Types**

- **`1.5`**의 내용은 배경지식이 없으면 한 번에 이해하기 어려울 것입니다.
- 나중에 더 자세히 언급하고 충분히 연습해야하는 부분이므로 가볍게 훑는 정도로 이해하면 됩니다.

#### 1.5.1. Objects

- 파이썬의 모든 것은 객체(object)입니다.
- **객체**란 **(1) 데이터와 (2) 그 데이터에 연산을 할 수 있는 함수를 포함한 것**입니다.
- 객체 속 함수는 **메서드(method)**라고 부릅니다.
    - 자세한 내용은 나중에 다루니 용어 정도만 알아두시면 됩니다.
- 객체 내부에 어떤 데이터가 있는지, 어떤 메서드를 지원하는지 확인하기 위해선 변수 뒤에 `TAB`을 누르면 됩니다.
    - 그러면 아래와 같이 변수 이름 오른쪽에 데이터 및 메서드 이름을 나열할 것입니다.

![image.png]()

- 위쪽 및 아래쪽 화살표를 사용하여 스크롤할 수 있습니다.
- 이 방법을 **탭 완성(tab completion)**이라고 부릅니다.
- 아래에서 예시와 함께 해보겠습니다. 메서드 `split`을 찾을 때까지 계속 아래로 이동합니다.

In [ ]:
# 'x' 뒤에 마침표를 입력한 다음 TAB을 누릅니다.
x.

- `split` 메서드를 찾았다면 그 뒤에 괄호를 추가하여 메서드를 사용할 수 있습니다.

In [ ]:
x.split()

['something', 'else']

#### 1.5.2. Types

- 우리는 종종 **자료형(type)**이라고 하는 **어떤 값이 어떤 종류의 객체인지 식별**하기를 원합니다.
- 자료형은 해당 자료형의 모든 인스턴스(instance)에 대한 일련의 연산들(operations)을 정의한 추상적 대상입니다.
    - 말이 어렵고 나중에 더 자세히 언급되므로 넘어가도 됩니다.
- 즉, `2.0` 및 `3.0`은 실수형(float)이라는 자료형의 인스턴스이며 실수형에는 적용할 수 있는 공통적인 연산들의 집합이 존재합니다.
    - 아직 배우진 않았지만 직관적으로 생각하면 실수끼리는 더할 수 있습니다. 예를 들어 `2.0 + 3.0`은 `5.0`이 될 것입니다. 이처럼 덧셈 `+`는 실수형의 연산이 됩니다.
- 특히 자료형에 따라 다음이 결정됩니다.
    - 자료형의 인스턴스로 사용 가능한 데이터 (각 인스턴스는 데이터의 서로 다른 값을 가질 수 있습니다).
    - 해당 객체 및 데이터에 적용할 수 있는 메서드.
- `type` 함수를 사용하여 어떤 값의 자료형을 알아낼 수 있습니다.
- `type` 함수는 자료형을 알고자하는 값을 단일인자로 가지고 해당 인자의 자료형을 출력합니다.
- 다음 코드들을 한 번씩 실행해봅시다.
    - `3`의 자료형은 `int`, `“Hello World”`의 자료형은 `str`, `[1, 2, 3]`의 자료형은 `list`로 출력될 것입니다.
    - 각 자료형들을 어떻게 다루는지에 대해서는 나중에 더 자세히 배울 예정입니다.

In [ ]:
type(3)

int

In [ ]:
type("Hello World")

str

In [ ]:
type([1, 2, 3])

list

### **1.6. Modules**

- 파이썬에서는 각종 사용할 수 있는 도구들에 대하여 모듈방식(modular appraoch)을 취합니다.
- 이는 **비슷한 도구들을 하나의 패키지(package)로 함께 모아놓았다**는 것을 의미합니다. (패키지는 모듈이라고도 합니다.)
- 예를 들어 앞으로 자주 사용할 패키지들에는 이런 것들이 있습니다.
    - `pandas`는 데이터 분석을 위한 여러 툴을 모아놓은 패키지입니다.
    - `matplotlib` 는 시각화를 위한 여러 툴을 모아놓은 패키지입니다.
    - `requests`와  `urllib`는 인터넷이 연결된 환경으로부터 여러 가지 작업을 수행할 수 있는 툴을 모아놓은 패키지입니다.
- 위의 패키지들의 사용법은 앞으로 충분한 연습을 통해 익히는 것이 좋습니다.
- 아래처럼 작성하여 패키지의 기능을 현재 파이썬 세션으로 가져올 수 있습니다.
```python
import package
```
- 한 번만 실행해주면 세션이 열려있는 동안 `package.name`을 입력하면 패키지의 함수나 객체에 접근할 수 있습니다.
- 예를 들어 다음과 같습니다.

In [ ]:
import sys   # 컴퓨터 시스템을 다루기 위한 패키지입니다.
sys.version  # 사용중인 파이썬의 버전 정보를 출력합니다.

'3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]'

#### 1.6.1. Module Aliases

- 매번 `package.name`을 입력하기에는 긴 이름(예를 들어, `matplotlib`)을 가진 패키지들이 있어 패키지 기능에 액세스하는 것이 다소 불편합니다.
- 이 부담을 덜기 위해 파이썬에서는 패키지에 별칭 또는 닉네임을 부여할 수 있습니다.
    - 아래의 형식으로 코드를 작성하면 됩니다.
```python
import package as p
```
- 이를 사용하면 `package.function_name`이 아닌 `p.function_name`으로 패키지 기능에 액세스할 수 있습니다.
- 주로 사용하는 별칭은 다음과 같습니다.
    - `import pandas as pd`
    - `import numpy as np`
    - `import matplotlib as mpl`
    - `import datetime as dt`
- 별칭에 대해서는 아무 이름이나 선택할 수 있지만 일반적으로 이용되는 이름을 사용하는 것이 좋습니다.
    - 그 이유는 코드의 가독성때문입니다. 가독성이 중요한 이유는 **`1.7`**절에서 확인하실 수 있습니다.
- 주로 사용하는 패키지의 별명은 경험이 쌓일수록 자연스럽게 익힐 것입니다.

### **1.7. Good Code Habits**

- 소프트웨어공학 세계에서는 다음과 같은 말이 통용됩니다.

> ⚠️ 항상 당신의 코드를 유지보수하는 자가 당신이 사는 곳을 아는 공격적인 사이코패스라고 생각하고 코드를 짜라. 즉 **가독성(readability)**을 늘 신경쓰며 코드를 작성한다.

- 가독성이 좋은 코드란 **읽고 이해하기 쉬운 코드**를 말합니다.
- 위의 말은 굉장히 극단적이긴 하지만 그만큼 **코드의 정확성(correctness)**만큼 중요한 것이 **코드의 가독성**임을 의미합니다.
- 따라서 코드를 작성할 때는 코드를 가능한 한 읽기 쉽게 만들기 위해 최선을 다해야 합니다.
- 다음은 **가독성이 좋은 코드를 만들기 위해 자주 쓰이는 몇 가지 방법들**입니다.
    - **주석을 자주 씁니다.**  코드에 짧은 메모를 남겨놓게 되면 자신의 코드를 이용하는 다른 사람들에게 도움이 될 뿐만 아니라 나중에 코드를 작성한 본인이  코드를 해석하는 데에도 도움이 됩니다. 개인적으로는 조사나 어미 등을 생략하게 되면 중의적으로 해석될 여지가 커서 완결된 문장으로 작성하는 것을 선호합니다.
    - **쉼표를 쓸 때마다 그 뒤에는 한 칸의 여백을 둡니다.**  예를 들어 `print()` 함수를 쓸 때 여러 인자를 출력하고 싶다면 `print(a,b,c)`보다는 `print(a, b, c)`처럼 작성하는 것이 좋습니다.
    - **공백(whitespace)은 당신의 친구입니다.** 코드 줄 다음에 연이어 줄을 쓰지 않는 것이 좋습니다. 빈 줄을 사용하여 다른 기능의 코드끼리 나눕니다.
    - **한 줄이 너무 길어지지 않게 합니다.** 코드를 읽는 일부 사람들은 랩톱처럼 일반 모니터보다 작은 모니터로 코드를 읽는 경우가 있습니다. 이때 코드를 읽기 위해 가로로 스크롤할 필요가 없도록 하는 것이 좋습니다. 예를 들어 한 줄에 80자 이하를 권장합니다.
- 이외에도 여러 방법들이 있지만 아직 배우지 않은 개념이 많기때문에 나중에 언급할 예정입니다.

---

## **2. Numbers, Dates, and Times**

- 지금까지 파이썬을 이용하여 프로그래밍의 기초 개념에 대하여 알아보았습니다!
- 이젠 **숫자형 자료와 날짜를 파이썬으로 다루는 방법**에 대해 알아보겠습니다.

### **2.1. Integers, Floating Point Numbers, Complex Numbers**

- 파이썬에는 여러 종류의 숫자 자료형이 있습니다.
- 우선 두 가지로 시작해봅시다.
    1. **정수형 (`int`)**: 이름에서 쉽게 알 수 있듯 정수형은 정수의 값만을 취합니다.
        - 예를 들어, -2, -1, 0, 1, 2 등이 있습니다.
    2. **실수형(부동소수점 수) (`float`)**: 쉽게 생각해서, 1.0, 3.1415, 또는 100.0223589232와 같은 실수값을 가진다고 생각하면 됩니다.
- 위 두 자료형을 구분하는 가장 쉬운 방법은 **소수점이 있는지 없는지를 확인**하는 것입니다.
- `float` 자료형에는 소수점이 있고, `int` 자료형은 소수점을 가지지 않습니다.
- 아래에서 `xi`와 `zi`에는 정수형을, `xf`와 `zf`에는 실수형 자료를 할당해보겠습니다.

In [ ]:
xi = 1
xf = 1.0
zi = 123
zf = 1230.5  # 아무리 큰 수라고 하더라도 쉼표로 구분할 수 없습니다.
zf1 = 1_230.5 # 대신 밑줄을 통상 쓰는 쉼표처럼 이용할 수 있습니다.

- 또다른 숫자형 자료로 복소수형(`complex`)이 있습니다.
- 복소수형 자료는 `a + bj`의 꼴 혹은 `complex(a, b)`를 가집니다.
- 여기서 중요한 것은 `j`의 유무입니다.
    - `j`는 허수 i를 뜻합니다.
- 같은 `1`을 나타내더라도 `1`은 정수형, `1 + 0j`는 복소수형 자료입니다.
    - 마찬가지로 `1.` 혹은 `1.0`은 실수형 자료입니다.
- 전에 배운 `type()` 함수로 1의 세 표현의 자료형을 확인해봅시다.

In [ ]:
type(1)

int

In [ ]:
type(1.)

float

In [ ]:
type(1+0j)

complex

#### 2.1.1. Python as a Calculator

- 숫자를 다룰 수 있다면, 숫자끼리의 연산도 가능하면 더 많은 일을 할 수 있겠죠?
- 파이썬에서는 마치 계산기처럼 숫자형 자료끼리의 수학적 연산이 가능합니다.
- 간단한 예로, 숫자를 할당받은 두 변수 간에 사칙연산과 거듭제곱을 수행하여 `print()` 함수로 그 계산 결과를 출력해봅시다.
    - `print()` 함수에서 여러 인자를 쉼표로 구분하여 입력하면 각 인자가 한 칸의 공백과 함께 한 줄로 출력됩니다.
    - 예를들어, `print(1, 2)`는 `1 2`를 출력합니다.

In [ ]:
a = 4
b = 2

print("a + b is", a + b)
print("a - b is", a - b)
print("a * b is", a * b)
print("a / b is", a / b)
print("a ** b is", a**b)
print("a ^ b is", a^b)

a + b is 6
a - b is 2
a * b is 8
a / b is 2.0
a ** b is 16
a ^ b is 6

- 기호를 확인했을 때 사칙연산은 직관적으로 이해가 되어도 마지막은 두 줄은 직관적이지 않습니다.
- 파이썬에서의 거듭제곱의 기호는 `**`입니다.
- 즉 `4 ** 2`는 '4의 제곱'을 의미합니다.
- `^`를 썼음에도 오류가 나지 않고 다른 값을 출력하는 것으로 보아 `^`도 어떤 연산을 수행하는 것같습니다.
    - 이는 나중에 언급하도록 하겠습니다.

- 이상한 점을 하나 더 확인해볼까요?
- 두 정수형 자료끼리의 연산 결과는 기본적으로 정수형이나, 실제세계에서 두 정수간 나눗셈의 결과가 실수일 수 있는 것처럼 파이썬에서도 이를 고려하여 나눗셈의 결과는 항상 실수형으로 합니다.

- 이제 두 변수에 실수형 자료를 할당하여 연산을 수행해봅시다.

In [ ]:
a = 4
b = 2.0

print("a + b is", a + b)
print("a - b is", a - b)
print("a * b is", a * b)
print("a / b is", a / b)
print("a ** b is", a**b)

a + b is 6.0
a - b is 2.0
a * b is 8.0
a / b is 2.0
a ** b is 16.0

- 이전 예시와 차이가 느껴지시나요?
- 아래 예시의 연산 결과는 모두 실수형입니다.
    - `a`와 `b`의 값이 모두 실수형이기 때문입니다.
- 만약 `a`와 `b` 중 하나는 정수형 자료를 할당하고 나머지 하나는 실수형 자료를 할당한다면 연산의 결과는 항상 실수형입니다.
    - 즉 둘 중 하나라도 실수형이면 항상 그 연산 결과는 실수형입니다.

In [ ]:
4.0 + 2

6.0

- 파이썬에서 복잡한 수학적 연산을 하는 경우에 헷갈리지 않기 위해서는 연산 순서를 알아야 합니다.
    1. 소괄호 `()`
    2. 거듭제곱 `**`
    3. 곱셈 `*`과 나눗셈 `/`
    4. 덧셈 `+`과 뺼셈 `-`
- 다음 예로 확인해봅시다.
    - 셀을 실행하기 전에 연산 결과를 예측해보세요.

In [ ]:
x = 2.0
y = 3.0

print(x + y * x)
print((x + y) * x)

8.0
10.0

- 현실에서 $\frac{1}{0}$을 계산할 수는 없으니 파이썬에서도 에러 메시지를 출력합니다.

In [ ]:
1/0

ZeroDivisionError: ignored

**[Exercise]**
- Create the following variables:
    - `D`: A floating point number with the value 10,000
    - `r`: A floating point number with value 0.025
    - `T`: An integer with value 30
- We will use them in a later exercise.

In [ ]:
# Please write your code here!

**[Exercise]**
- Remember the variables we created earlier?
- Let’s compute the present discounted value of a payment ($D$) made in $T$  years assuming an interest rate of 2.5%.
- Save this value to a new variable called `PDV` and print your output.
- The formula is
$$ PDV = \frac{D}{(1+r)^T}$$

In [ ]:
# Please write your code here!

#### 2.1.2. Other Math Functions

- 세상에 수학 연산이 사칙연산과 거듭제곱만 있는 것은 아닙니다. (그랬다면 정말 좋았겠지만요😅)
- 예를 들어 삼각함수인 사인함수가 있습니다.
- 파이썬에서 이를 내장함수로 구현해놓았을까요?
    - 한 번 실행해봅시다.

In [ ]:
sin(2.5)

NameError: ignored

- 아쉽게도 파이썬에서는 사인함수를 내장함수로 만들지 않았습니다.
- 그렇다면 어떻게 해야 할까요?
- 파이썬에서는 수학과 관련된 여러 추가적인 함수를 담은 패키지인 `math`를 불러와야 합니다.
- 다음 셀을 실행하여 `math` 패키지를 불러와봅시다.

In [ ]:
import math

- 이제 `math.`을 셀에 입력한 후 `[TAB]`을 눌러 사인함수처럼 보이는 것이 있는지 확인합니다.
- `sin()`이 가장 근접해보이므로 실행해봅시다.

In [ ]:
math.sin(2.5)

0.5984721441039565

- **[예제]** `math` 패키지를 이용하여 $e^{3} + 4^{e}$의 값을 구하시오. (답: `63.393597349963585`)

In [ ]:
# 여기 코드를 입력해보세요!

- **[예제]** `math.factorial?`을 실행하여 `math.factorial()`의 기능이 무엇인지, 어떤 인자를 입력해야 하는지 등을 파악하시오.

In [ ]:
# 여기 코드를 입력해보세요!
# 서술형 답안은 주석으로 작성해주세요!

- 이외에도 `math` 패키지를 이용하면 다른 다양한 수학 개념을 다룰 수 있습니다.
- 예를 들어 무한대도 표현할 수 있습니다.

In [ ]:
math.inf

inf

- 또는 숫자가 아니지만 숫자처럼 취급되고싶은 자료도 표현할 수 있습니다.
    - 이 말이 이해가 안가면 넘어가셔도 됩니다.

In [ ]:
math.nan

nan

- **[예제]** 다음 코드를 보며 그 실행 결과를 예측하시오.

In [ ]:
1 / math.inf

0.0

In [ ]:
math.inf * 2

inf

In [ ]:
math.inf / math.inf

nan

- 추가로, `math.log`와 `math.sin` 대신 패키지를 불러올 때 `from math import log, sin`을 앞줄에 써준 뒤 실행하면 `log`와 `sin`만 적어도 됩니다.
- 이 방법은 특정 패키지에서 필요한 함수가 제한적인 경우에 이용합니다.

In [ ]:
from math import log, sin

In [ ]:
print(log(20), sin(20))

2.995732273553991 0.9129452507276277

**[Exercise]**
- Verify the “trick” where the percent difference ($\frac{x-y}{x}$) between two numbers close to 1 can be well approximated by the difference between the log of the two numbers ($log(x)-log(y)$).
- Use the numbers `x` and `y` below.
- you will want to use the `math.log` function

In [ ]:
x = 1.05
y = 1.02

# Please write your code here!

#### 2.1.3. Floor/Modulus Division Operators

- 다음으로 배울 내용은 앞으로 잘 쓰게될 연산자는 아니지만 알고 있으면 유용하므로 알고있는 것이 좋습니다.
- 각각 숫자형 자료가 할당된 변수 `x`와 `y`에 대하여,
    - 버림 나눗셈(Floor division): `x // y`; `x`를 `y`로 나눈 몫을 구합니다.
    - 모듈로 연산자(Modulus division): `x % y`; `x`를 `y`로 나눈 나머지를 구합니다.
- 예시로 37을 7로 나누었을 때의 몫과 나머지를 생각해봅시다.
    - `37 // 7` = 5 (7 * 5 = 35)
    - `37 % 2` = 2 (2 + 35 = 37)
- 직접 코드를 실행해봅시다!

In [ ]:
print(37 // 7) # Floor Division
print(37 % 7) # Modulus Division

5
2

- 이 방법이 아니어도, `divmod()`를 이용하면 나눗셈의 결과인 몫과 나머지를 한 번에 구할 수 있습니다.
- `divmod()`의 설명을 확인하고 위의 예시를 그대로 실행해봅시다.

In [ ]:
divmod?

- 아직 배우지 않은 용어들이 나오지만 중요한 사실은 입력된 인자 `x`와 `y`에 대하여 `x // y`와 `x % y`의 값을 모두 계산해준다는 사실입니다.

In [ ]:
divmod(37, 7)

(5, 2)

- 실행결과 무엇인지는 모르지만(나중에 튜플임을 배웁니다.) 괄호 안에 두 수가 묶여나오는데 앞의 수는 몫을, 뒤의 수는 나머지임을 쉽게 알 수 있습니다.

### **2.2. Other Numbers**

- 파이썬에서는 **`2.1`**에서 배운 세 가지 숫자형 자료 외에도 다른 자료형이 존재합니다.
- 금융데이터분석에서는 **`2.1`**에서 배운 것만 알고 있어도 큰 문제는 없으나 상식의 차원에서 어떤 수가 있는지 간단히 짚고 넘어가겠습니다.

#### 2.2.1. Scientific Notations

- 새로운 자료형은 아니지만 파이썬에서는 과학적 기수법(scientific notation)을 지원합니다.
- 과학적 기수법이란 너무 큰 수나 작은 수를 효율적으로 작성할 수 있도록 만든 표기 체계입니다.
- 아주 쉽습니다.
    - `1e10`은 1 × 10^10을 의미합니다.
    - 즉 e가 자연상수가 아닌 10을 e 뒤에 나온 수만큼 10의 거듭제곱을 한 후 e앞의 수를 곱함을 의미합니다.
    - e 앞의 수는 통상 1부터 10 사이의 수만을 입력합니다.
- 과학적 기수법으로 작성한 수 자체는 파이썬에서 실수형(float)으로 받아들입니다.

- 예시를 통해 확인합시다.

In [ ]:
# 과학적 기수법 형식으로 작성한 수의 자료형을 확인합니다.

type(1e3)

float

In [ ]:
# 2를 과학적 기수법으로 나타냅니다.

2e0

2.0

In [ ]:
# 1530을 과학적 기수법으로 나타냅니다.

1.53e3

1530.0

#### 2.2.2. Binary Numbers

- 지금까지 배운 숫자 자료형은 10진법(decimal) 체계입니다.
- 파이썬에서는 10진법 외에도 2진법, 8진법, 16진법을 지원합니다.
- 공학에서는 많이 쓰이지만 지금 자세히 알 필요는 없으므로 간단한 예시를 통해 확인하고 넘어가겠습니다.

- 2진법은 0과 1 두 수로 이루는 수 표현체계입니다. (0, 1)

In [ ]:
# 파이썬에서 2진수는 숫자 앞에 '0b'가 붙는다.

0b10

2

In [ ]:
# 2진수를 10진수로 변환한다.

int(0b10)

2

In [ ]:
# 10진수를 2진수로 변환한다.

bin(10)

'0b1010'

#### 2.2.3. Octal Numbers

- 8진법은 0부터 7까지의 8개 수로 이루는 수 표현체계입니다. (0, 1, 2, 3, 4, 5, 6, 7)
- 마찬가지로 간단한 예시로 확인하고 넘어가겠습니다.

In [ ]:
# 파이썬에서 8진수는 숫자 앞에 '0b'가 붙는다.

0o10

8

In [ ]:
# 8진수를 10진수로 변환한다.

int(0o10)

8

In [ ]:
# 10진수를 8진수로 변환한다.

oct(10)

'0o12'

#### 2.2.4. Hexadecimal

- 16진법은 0부터 9, 그리고 A부터 F까지의 16개 문자로 이루는 수 표현체계입니다. (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F)
- 마찬가지로 간단한 예시로 확인하고 넘어가겠습니다.

In [ ]:
# 파이썬에서 16진수는 숫자 앞에 '0x'가 붙는다.

0xA0

160

In [ ]:
# 16진수를 10진수로 변환한다.

int(0xA0)

160

In [ ]:
# 10진수를 16진수로 변환한다.

hex(160)

'0xa0'

- ⚠️ **`2.3`**부터 영어를 사용하게 됩니다.
- 심화된 내용으로 진입하는 구간이어서 번역을 시도한 결과 오히려 내용이 헷갈릴 수도 있겠다고 생각하여 원문 그대로 남겨놓았습니다.
- 엄청나게 어려운 영어가 쓰인 것은 아니니 모르는 단어는 검색해보며 따라가도 충분히 이해하실 수 있을 것입니다.🙇‍♂️

### **2.3. Representation of Numbers**

- 주차별 분량 조절을 위하여 2주차 학습내용으로 변경되었습니다.

### **2.4. Dates and Times**

- 주차별 분량 조절을 위하여 3주차 학습내용으로 변경되었습니다.

---

## **3. Logical Expressions and Operators**

### **3.1. Logical Expressions**

- A **logical expression** is a statement that can either be **true or false**.
- For example, 'a < b' is a logical expression.
- It can be true or false depending on what values of a and b are given.
- Note that this differs from a **mathematical expression** which denotes a truth statement.
- In the previous example, the mathematical expression 'a < b' means that a is less than b, and values of a and b where a ≥ b are not permitted.
- Logical expressions form the basis of computing, so for the purposes of this book, **all statements are assumed to be logical rather than mathematical** unless otherwise indicated.

### **3.2. Booleans**

- In Python, a logical expression that is true will compute to the value “True”.
- A false expression will compute to the value “False”.
- This is a new data type we come across - **boolean**, which has the built-in values True and False.
- For the purpose of this note, **“True” is equivalent to 1**, and **“False” is equivalent to 0**.
- Distinguishing between the numbers 1 and 0 and the logical values “True” and “False” is beyond the scope of this book, but it is covered in more advanced books on computing.
- Logical expressions are used to pose questions to Python.
    - For example, “3 < 4” is equivalent to, “Is 3 less than 4?”
    - Since this statement is true, Python will compute it as 1.
    - However, "3 > 4" is false, therefore Python will compute it as 0.
- Let’s start by creating some booleans and looking at them.

In [ ]:
x = True
y = False

type(x)

bool

In [ ]:
x

True

In [ ]:
y

False

### **3.3. Comparison Operators**

- **Comparison operators** compare the value of two numbers, and they are used to build logical expressions.
- Python reserves the symbols >, >=, <, <=, !=, ==, to denote “greater than”, “greater than or equal”, “less than”, “less than or equal”, “not equal”, and “equal”, respectively.
- Let’s start with an example a = 4, b = 2, and see the following table:

<center>

| 연산자 | 설명 | 예시 | 출력결과 |
| --- | --- | --- | --- |
| == | equal | `a == b` | `False` |
| != | not equal | `a != b` | `True` |
| > | greater than | `a > b` | `True` |
| >= | greater than or equal | `a >= b` | `True` |
| < | less than | `a < b` | `False` |
| <= | less than or equal | `a <= b` | `False` |

</center>

- We demonstrate these below.

In [ ]:
a = 4
b = 2

print("a > b", "is", a > b)
print("a < b", "is", a < b)
print("a == b", "is", a == b)
print("a >= b", "is", a >= b)
print("a <= b", "is", a <= b)

a > b is True
a < b is False
a == b is False
a >= b is True
a <= b is False

### **3.4. Logical Operators**

- **Logical operators** are operations between two logical expressions that, for the sake of discussion, we call P and Q.
- The fundamental logical operators we will use herein are **and**, **or**, and **not**.
- The **truth table** of a logical operator or expression gives the result of every truth combination of P and Q.
- The truth tables for “and”, “or”, and “not” are given in the following figure.

<center>

| P | Q | P and Q | P or Q | not P |
| --- | --- | --- | --- | --- |
| True | True | True | True | False |
| True | False | False | True | False |
| False | True | False | True | True |
| False | False | False | False | True |

</center>

#### 3.4.1. Negation `not`

- Occasionally, **determining whether a statement is “not true” or “not false” is more convenient than simply “true” or “false”***.
- This is known as **negating** a statement.
- In Python, we can negate a boolean using the word `not`.

In [ ]:
not False

True

In [ ]:
not True

False

#### 3.4.2. Multiple Comparisons : Conjunction `and` and Disjunction `or`

- Sometimes we need to evaluate multiple comparisons at once.
- This is done by using the words `and` and `or`.
- However, these are the “mathematical” *and*s and *or*s – so they don’t carry the same meaning as you’d use them in colloquial English.
    - `a and b` is true only when **both** `a` and `b` are true.
    - `a or b` is true whenever **at least one** of `a` or `b` is true.
- For example,
    - The statement “I will accept the new job if the salary is higher *and* I receive more vacation days” means that you would only accept the new job if you both receive a higher salary and are given more vacation days.
    - The statement “I will accept the new job if the salary is higher *or* I receive more vacation days” means that you would accept the job if (1) they raised your salary, (2) you are given more vacation days, or (3) they raise your salary and give you more vacation days.
- Let’s see some examples.

In [ ]:
True and True

True

In [ ]:
True and False

False

In [ ]:
False or True

True

In [ ]:
False or False

False

In [ ]:
# Can chain multiple comparisons together.
True and (False or True)

True

- Just as with arithmetic operators, logical operators have an **order of operations** relative to each other and in relation to arithmetic operators.
- **All arithmetic operations will be executed before comparison operations**, which will be **executed before logical operations**.
- **Parentheses** can be used to change the order of operations.

In [ ]:
1 + 3 > 2 + 5

False

- Even when the order of operations is known, it is usually **helpful for you and those reading your code to use parentheses to make your intentions clearer**.
- In the preceding example (1 + 3) > (2 + 5) is clearer.

- In Python’s implementation of logic, 1 is used to denote true and 0 for false. However, 1 and 0 are still numbers.
- Therefore, Python will allow abuses such as: (3 > 2) + (5 > 4), which will resolve to 2.

In [ ]:
(3 > 2) + (5 > 4)

2

- Although in formal logic, 1 is used to denote true and 0 to denote false, Python slightly abuses notation and it will take any number not equal to 0 to mean true when used in a logical operation.
- For example, 3 and 1 will compute to true.
- Do not utilize this feature of Python.
- **Always use 1 to denote a true statement**.

**[Exercise]**
- Without typing the commands, determine whether the following statements are true or false.
- Once you have evaluated whether the command is `True` or `False`, run the code in Python.

In [77]:
x = 2
y = 2
z = 4

# Statement 1
x > z

# Statement 1
x == y

# Statement 3
(x < y) and (x > y)

# Statement 4
(x < y) or (x > y)

# Statement 5
(x <= y) and (x >= y)

# Statement 6
True and ((x < z) or (x < y))

True

### **3.5. Quantifiers**

- We have seen how we can use the words `and` and `or` to process two booleans at a time.
- The functions `all` and `any` allow us to process an unlimited number of booleans at once.

#### 3.5.1. Universal Quantifier

- Let $P_1$, $P_2$, $P_3$, $\cdots$, $P_n$ be statements where we can determine either it is true or false.
- Then `all([P_1, P_2, ⋯, P_n])` is equivalent to `P_1 and P_2 and ⋯ and P_n`.
- That is, `all(bools)` will return `True` if and only if all the booleans in `bools` is `True` and returns `False` otherwise.

In [ ]:
all([True, True, True])

True

In [ ]:
all([False, True, False])

False

In [ ]:
all([False, False, False])

False

- **[NOTE]** For now, do not worry about what the `[` and `]` mean – they allow us to create lists which we will learn about in an upcoming lecture.

#### 3.5.2. Existential Quantifier

- Let $P_1, P_2, P_3, \cdots, P_n$ be statements where we can determine either it is true or false.
- Then `any([P_1, P_2, ⋯, P_n])` is equivalent to `P_1 or P_2 or P_2 or ⋯ or P_n`.
- That is, `any(bools)` returns `True` whenever one or more of `bools` is `True`.

In [ ]:
any([True, True, True])

True

In [ ]:
any([False, True, False])

True

In [ ]:
any([False, False, False])

False

---

## **4. Strings**

### **4.1. Generating a String**

- **Textual information** is stored in a data type called a **string(문자열)**.
- To denote that you would like something to be stored as a string, you **place it inside of quotation marks**.
- For example,
```python
"this is a string"  # Notice the quotation marks
'this is a string'  # Notice the quotation marks
this is not a string  # No quotation marks
```

- You can use either `"` or `'` to create a string.
- Just make sure that you **start and end the string with the same one**!
- Notice that if we ask Python to tell us the type of a string, it abbreviates its answer to str.

In [61]:
type("this is a string")

str

**[Exercise]**
- The code below is invalid Python code
```python
x = 'What's wrong with this string'
```
- Can you fix it?

In [62]:
# Please Write your code here!

### **4.2. String Operations**

- Some of the arithmetic operators we saw in the numbers lecture also work on strings:
    - Put two strings together: `x + y`.
    - Repeat the string `x` a total of `n` times: `n * x` (or `x * n`).

In [63]:
x = "Hello"
y = "World"

In [64]:
x + y

'HelloWorld'

In [65]:
3 * x

'HelloHelloHello'

- What happens if we try `*` with two strings, or `-` or `/`?
- The best way to find out is to try it!

In [66]:
a = "1"
b = "2"
a * b

TypeError: ignored

In [67]:
a - b

TypeError: ignored

**[Exercise]**
- Using the variables `x` and `y`, how could you create the sentence `Hello World`?

**[Hint]**
- Think about how to represent a space as a string.

In [ ]:
# Please Write your code here!

### **4.3. String Methods**

- We can use many methods to manipulate strings.
- We will not be able to cover all of them here, but let’s take a look at some of the most useful ones.

In [68]:
x

'Hello'

In [69]:
x.lower()  # Makes all letters lower case

'hello'

In [70]:
x.upper()  # Makes all letters upper case

'HELLO'

In [71]:
x.count("l")  # Counts number of a particular string

2

In [72]:
x.count("ll")

1

**[Exercise]**
- One of our favorite (and most frequently used) string methods is `replace`.
- It substitutes all occurrences of a particular pattern with a different pattern.
- For the variable `test` below, use the replace method to change the `c` to a `d`.

**[Hint]**
- Type `test.replace?` to get some help for how to use the method replace.

In [ ]:
test = "abc"

# Please Write your code here!

**[Exercise]**
- Suppose you are working with price data and encounter the value `"$6.50"`.
- We recognize this as being a number representing the quantity “six dollars and fifty cents.”
- However, Python interprets the value as the string `"$6.50"`. (Quiz: why is this a problem? Think about the examples above.)
- In this exercise, your task is to convert the variable `price` below into a number.

**[Hint]**
- Once the string is in a suitable format, you can call write `float(clean_price)` to make it a number.

In [ ]:
price = "$6.50"

# Please Write your code here!

### **4.4. String Formatting**

- Sometimes we’d like to reuse some portion of a string repeatedly, but still make some relatively small changes at each usage.
- We can do this with string formatting, which done by using `{}` as a placeholder where we’d like to change the string, with a variable name or expression.
- Let’s look at an example.

In [73]:
country = "Vietnam"
GDP = 223.9
year = 2017
my_string = f"{country} had ${GDP} billion GDP in {year}"
print(my_string)

Vietnam had $223.9 billion GDP in 2017

- Rather than just substituting a variable name, you can use a calculation or expression.

In [74]:
print(f"{5}**2 = {5**2}")

5**2 = 25

- Or, using our previous example

In [75]:
my_string = f"{country} had ${GDP * 1_000_000} GDP in {year}"
print(my_string)

Vietnam had $223900000.0 GDP in 2017

- In these cases, the `f` in front of the string causes Python interpolate any valid expression within the `{}` braces.

**[Exercise]**
- Lookup a country in [World Bank database](https://data.worldbank.org/), and format a string showing the growth rate of GDP over the last 2 years.

In [ ]:
# Please Write your code here!

- Alternatively, to reuse a formatted string, you can call the `format` method (noting that you do **not** put f in front).

In [76]:
gdp_string = "{country} had ${GDP} billion in {year}"

gdp_string.format(country = "Vietnam", GDP = 223.9, year = 2017)

'Vietnam had $223.9 billion in 2017'

**[Exercise]**
- Instead of hard-coding the values above, try to use the `country`, `GDP` and `year` variables you previously defined.

In [ ]:
# Please Write your code here!

**[Exercise]**
- Create a new string and **use formatting** to produce each of the following statements
    - “The 1st quarter revenue was 110M”
    - “The 2nd quarter revenue was 95M”
    - “The 3rd quarter revenue was 100M”
    - “The 4th quarter revenue was 130M”

In [ ]:
# Please Write your code here!

- For more information on what you can do with string formatting (there is a lot that can be done…), see the [official Python documentation](https://docs.python.org/3.6/library/string.html) on the subject.

---

## **5. Collections**

### **5.1. Ordered Collections**

#### 5.1.1. Lists

- A Python `list` is an **ordered collection of items**.
- We can create lists using the following syntax:
```python
[item1, item2, ⋯, itemN]
```
- Each item can be of any type.
- Let’s create some lists.

In [1]:
# created, but not assigned to a variable

[2.0, 9.1, 12.5]

[2.0, 9.1, 12.5]

In [2]:
# stored as the variable `x`

x = [2.0, 9.1, 12.5]
print("x has type", type(x))
x

x has type <class 'list'>

[2.0, 9.1, 12.5]

##### 5.1.1.1. What can we do with Lists?

- We can **access items in a list** called `mylist` using `mylist[N]` where `N` is an integer(`int`).
- **[Note]** Anytime that we use the syntax `x[i]` we are doing what is called **indexing** – it means that we are **selecting a particular element of a collection** `x`.

In [3]:
x[1]

9.1

- Wait? Why did `x[1]` return `9.1` when the first element in x is actually `2.0`?
- This happened because Python starts counting at zero!
- Lets repeat that one more time for emphasis **Python starts counting at zero!**
- To access the first element of x we must use `x[0]`:

In [4]:
x[0]

2.0

- We can also determine **how many items are in a list** using the `len()` function.

In [5]:
len(x)

3

- What happens if we try to index with a number higher than the number of items in a list?

In [6]:
x[4]

IndexError: ignored

- We can check **if a list contains an element** using the `in` keyword.

In [7]:
2.0 in x

True

In [8]:
1.5 in x

False

- For our list x, there are other common operations we might want to do.

In [9]:
x.reverse() # 원소를 역순으로 정리한다.
x

[12.5, 9.1, 2.0]

In [10]:
number_list = [10, 25, 42, 1.0]
print(number_list)

number_list.sort() # 오름차순 혹은 내림차순으로 원소를 정리한다. 오름차순과 내림차순을 정하는 방법은 무엇일까? `?`을 이용하자.
print(number_list)

[10, 25, 42, 1.0]
[1.0, 10, 25, 42]

- Note that in order to `sort`, we had to have all elements in our list be numbers (`int` and `float`), more on this below.
- We could actually do the same with a list of strings.
- In this case, sort will put the items in alphabetical order.

In [11]:
str_list = ["NY", "AZ", "TX"]
print(str_list)

str_list.sort()
print(str_list)

['NY', 'AZ', 'TX']
['AZ', 'NY', 'TX']

- The `append` method **adds an element to the end of existing list**.

In [12]:
num_list = [10, 25, 42, 8]
print(num_list)

num_list.append(10)
print(num_list)

[10, 25, 42, 8]
[10, 25, 42, 8, 10]

- However, if you call `append` with a list, it adds a `list` to the end, rather than the numbers in that list.

In [13]:
num_list = [10, 25, 42, 8]
print(num_list)

num_list.append([20, 4]) # 리스트 속 원소가 아닌 리스트 자를 원소로서 추가한다.
print(num_list)

[10, 25, 42, 8]
[10, 25, 42, 8, [20, 4]]

- To combine the lists instead…

In [14]:
num_list = [10, 25, 42, 8]
print(num_list)
num_list.extend([20, 4])
print(num_list)

[10, 25, 42, 8]
[10, 25, 42, 8, 20, 4]

**[Exercise]**
- In the first cell, try `y.append(z)`.
- In the second cell try `y.extend(z)`.
- Explain the behavior.

In [ ]:
y = ["a", "b", "c"]
z = [1, 2, 3]

# Please write your code here

print(y)

In [ ]:
y = ["a", "b", "c"]
z = [1, 2, 3]

# Please write your code here

print(y)

#### 5.1.2. Lists of Different Types

- While most examples above have all used a `list` with a single type of variable, this is not required.
- Let’s carefully make a small change to the first example: replace `2.0` with `2`

In [15]:
x = [2, 9.1, 12.5]

- This behavior is identical for many operations you might apply to a list.
- Below we have also introduced a new module, Numpy, which provides many functions for working with numeric data.

In [16]:
import numpy as np

x = [2, 9.1, 12.5]

np.mean(x) == sum(x)/len(x)

True

- Taking this further, we can **put completely different types of elements** inside of a list.

In [17]:
# stored as the variable `x`
x = [2, "hello", 3.0]

print("x has type", type(x))
x

x has type <class 'list'>

[2, 'hello', 3.0]

- To see the types of individual elements in the list:

In [18]:
print(f"type(x[0]) = {type(x[0])}, type(x[1]) = {type(x[1])}, type(x[2]) = {type(x[2])}")

type(x[0]) = <class 'int'>, type(x[1]) = <class 'str'>, type(x[2]) = <class 'float'>

- While no programming limitations prevent this, you should be **careful if you write code with different numeric and non-numeric types in the same list**.
    - For example, if the types within the list cannot be compared, then how could you sort the elements of the list?
    - i.e. How do you determine whether the string “hello” is less than the integer 2, “hello” < 2?

In [19]:
x = [2, "hello", 3.0]

x.sort()

TypeError: ignored

- A few key exceptions to this general rule are:
    - Lists with **both integers and floating points are less error-prone**(since mathematical code using the list would work with both types).
    - When working with lists and data, you may want to **represent missing values with a different type than the existing values**.

#### 5.1.3. The `range` Function

- One function you will see often in Python is the `range` function. (자주 쓰이니 반드시 알아놓도록 합니다.)
- It has three versions:
    1. `range(N)`: goes from 0 to N-1
    2. `range(a, N)`: goes from a to N-1
    3. `range(a, N, d)`: goes from a to N-1, counting by d

- When we call the `range` function, we get back something that has type `range:

In [20]:
r = range(5)
print("type(r)", type(r))

type(r) <class 'range'>

- To turn the range into a list:

In [21]:
list(r)

[0, 1, 2, 3, 4]

**[Exercise]**
- Experiment with the other two versions of the `range` function.

In [22]:
# try list(range(a, N)) -- you pick `a` and `N`

In [ ]:
# try list(range(a, N, d)) -- you pick `a`, `N`, and `d`

#### 5.1.4. Tuples

- Tuples are very similar to lists and hold ordered collections of items.
- However, tuples and lists have three main differences:
    1. Tuples are created using parenthesis — `(` and `)` — instead of square brackets — `[` and `]`.
    2. Tuples are **immutable**, which is a fancy computer science word meaning that **they can’t be changed or altered after they are created**.
    3. Tuples and multiple return values from functions are tightly connected, as we will see in functions. (7절에서 더 자세히 언급할 예정입니다.)

In [23]:
t = (1, "hello", 3.0)

print("t is a", type(t))
t

t is a <class 'tuple'>

(1, 'hello', 3.0)

- We can convert a list to a tuple by calling the `tuple` function on a list.

In [24]:
print("x is a", type(x))
print("tuple(x) is a", type(tuple(x)))
tuple(x)

x is a <class 'list'>
tuple(x) is a <class 'tuple'>

(2, 'hello', 3.0)

- We can also convert a tuple to a list using the `list` function.

In [25]:
list(t)

[1, 'hello', 3.0]

- As with a list, we access items in a tuple `t` using `t[N]` where N is an int.

In [26]:
t[0]  # still start counting at 0

1

In [27]:
t[2]

3.0

**[Exercise]**
- Verify that tuples are indeed immutable by attempting the following:
    - Changing the first element of `t` to be 100
    - Appending a new element `"!!"` to the end of `t` (remember with a list `x` we would use `x.append("!!")` to do this)
    - Sorting `t`
    - Reversing `t`

In [ ]:
# change first element of t

In [ ]:
# appending to t

In [ ]:
# sorting t

In [ ]:
# reversing t

#### 5.1.5. Lists vs. Tuples

- Should you use a list or tuple?
- This depends on what you are storing, whether you might **need to reorder the elements**, or **whether you’d add new elements without a complete reinterpretation of the underlying data**.
    - For example, take data representing the GDP (in trillions) and population (in billions) for China in 2015.

In [28]:
china_data_2015 = ("China", 2015, 11.06, 1.371)

print(china_data_2015)

('China', 2015, 11.06, 1.371)

- In this case, we have used a tuple since:
    - (a) ordering would be meaningless; and
    - (b) adding more data would require a reinterpretation of the whole data structure.
- On the other hand, consider a list of GDP in China between 2013 and 2015.

In [29]:
gdp_data = [9.607, 10.48, 11.06]
print(gdp_data)

[9.607, 10.48, 11.06]

- In this case, we have used a list, since adding on a new element to the end of the list for GDP in 2016 would make complete sense.
- Along these lines, collecting data on China for different years may make sense as a list of tuples (e.g. year, GDP, and population – although we will see better ways to store this sort of data in the Pandas section).

In [30]:
china_data = [(2015, 11.06, 1.371), (2014, 10.48, 1.364), (2013, 9.607, 1.357)]
print(china_data)

[(2015, 11.06, 1.371), (2014, 10.48, 1.364), (2013, 9.607, 1.357)]

- In general, a rule of thumb is to use a list unless you need to use a tuple.
- Key criteria for tuple use are when you want to:
    - ensure **the order of elements can’t change**
    - ensure **the actual values of the elements can’t change**
    - **use the collection as a key in a `dict`** (we will learn what this means soon)

#### 5.1.6. `zip` and `enumerate`

- Two functions that can be extremely useful are `zip` and `enumerate`.
- Both of these functions are best understood by example, so let’s see them in action and then talk about what they do.

In [31]:
gdp_data = [9.607, 10.48, 11.06]
years = [2013, 2014, 2015]
z = zip(years, gdp_data)
print("type(z)", type(z))

type(z) <class 'zip'>

- To see what is inside `z`, let’s convert it to a list.

In [32]:
list(z)

[(2013, 9.607), (2014, 10.48), (2015, 11.06)]

- Notice that we now have a list where each item is a tuple.
- Within each tuple, we have one item from each of the collections we passed to the `zip` function.
- In particular, the first item in z contains the first item from `[2013, 2014, 2015]` and the first item from `[9.607, 10.48, 11.06]`.
- The second item in `z` contains the second item from each collection and so on.

- We can **access an element in this** and then **unpack the resulting tuple directly into variables**.

In [33]:
l = list(zip(years, gdp_data))

x, y = l[0] # unpack the first element of `l`

print(f"year = {x}, GDP = {y}")

year = 2013, GDP = 9.607

- Now let’s experiment with `enumerate`.

In [34]:
e = enumerate(["a", "b", "c"])
print("type(e)", type(e))
e

type(e) <class 'enumerate'>

- Again, we call `list(e)` to see what is inside.

In [35]:
list(e)

[(0, 'a'), (1, 'b'), (2, 'c')]

- We again have a list of tuples, but this time, **the first element in each tuple is the index of the second tuple element in the initial collection**.
- Notice that the third item is `(2, 'c')` because `["a", "b", "c"][2]` is `'c'`

**[Exercise]**
- **Challenging**: For the tuple `foo` below, use a combination of `zip`, `range`, and `len` to mimic `enumerate(foo)`.
- Verify that your proposed solution is correct by converting each to a list and checking equality with `==`.

In [ ]:
foo = ("good", "luck!")

# Please write your code here!

- An important quirk of some iterable types that are not lists (such as the above `zip`) is that you cannot convert the same type to a list twice.
- This is because `zip`, `enumerate`, and `range` produce what is called a **generator**.
- A generator will **only produce each of its elements a single time**, so if you **call list on the same generator a second time**, it will not have any elements to iterate over anymore.
- For more information, refer to the [Python documentation](https://docs.python.org/3/howto/functional.html#generators).

In [36]:
gdp_data = [9.607, 10.48, 11.06]
years = [2013, 2014, 2015]

z = zip(years, gdp_data)

l = list(z)
print(l)

m = list(z)
print(m)

[(2013, 9.607), (2014, 10.48), (2015, 11.06)]
[]

### **5.2. Associative Collections**

#### 5.2.1. Dictionaries

- A **dictionary (or dict)** associates `key`s with `value`s.
- It will feel similar to a dictionary for words, where the keys are words and the values are the associated definitions.
- The most common way to create a `dict` is to use curly braces — `{` and `}` — like this:
```python
{"key1": value1, "key2": value2, ..., "keyN": valueN}
```

- The crucial part of the syntax is that **each key-value pair is written `key: value`** and that **these pairs are separated by commas — `,`**.
- Let’s see an example using our aggregate data on China in 2015.

In [37]:
china_data = {"country": "China", "year": 2015, "GDP" : 11.06, "population": 1.371}
print(china_data)

{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371}

- Unlike our above example using a `tuple`, a `dict` allows us to associate a name with each field, rather than having to remember the order within the tuple.
- Often, code that makes a dict is easier to read if we put each `key: value` pair on its own line. (Recall our earlier comment on using whitespace effectively to improve readability!)
- The code below is equivalent to what we saw above.

In [38]:
china_data = {
    "country": "China",
    "year": 2015,
    "GDP" : 11.06,
    "population": 1.371
}

- Most often, the keys (e.g. “country”, “year”, “GDP”, and “population”) will be strings, but we could also use numbers (`int`, or `float`) or even `tuple`s(or, rarely, a combination of types).
- The values can be **any** type and **different** from each other.

**[Exercise]**
- Create a new dict which associates stock tickers(주식종목코드) with its stock price.
- Here are some tickers and a price.
    - AAPL: 175.96
    - GOOGL: 1047.43
    - TVIX: 8.38

In [ ]:
# Please write your code here!

- This next example is meant to emphasize how values can be anything – including another dictionary.

In [39]:
companies = {"AAPL": {"bid": 175.96, "ask": 175.98},
             "GE": {"bid": 1047.03, "ask": 1048.40},
             "TVIX": {"bid": 8.38, "ask": 8.40}}
print(companies)

{'AAPL': {'bid': 175.96, 'ask': 175.98}, 'GE': {'bid': 1047.03, 'ask': 1048.4}, 'TVIX': {'bid': 8.38, 'ask': 8.4}}

#### 5.2.2. Getting, Setting, and Updating dict Items

- We can now ask Python to tell us the value for a particular key by using the syntax `d[k]`, where `d` is our `dict` and `k` is the key for which we want to find the value.
- For example,

In [40]:
print(china_data["year"])
print(f"country = {china_data['country']}, population = {china_data['population']}")

2015
country = China, population = 1.371

- **[Note]** when inside of a formatting string, you can use `'` instead of `"` as above to ensure the formatting still works with the embedded code.
- If we ask for the value of a key that is not in the dict, we will get an error.

In [41]:
china_data["inflation"]

KeyError: ignored

- We can also **add new items to a dict** using the syntax `d[new_key] = new_value`.
- Let’s see some examples.

In [42]:
print(china_data)
china_data["unemployment"] = "4.05%"
print(china_data)

{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371}
{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371, 'unemployment': '4.05%'}

- To **update the value**, we use assignment in the same way (which will create the key and value as required).

In [43]:
print(china_data)
china_data["unemployment"] = "4.051%"
print(china_data)

{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371, 'unemployment': '4.05%'}
{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371, 'unemployment': '4.051%'}

- Or we could **change the type**.

In [44]:
china_data["unemployment"] = 4.051
print(china_data)

{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371, 'unemployment': 4.051}

**[Exercise]**
- Look at [the World Factbook for Australia](https://www.cia.gov/the-world-factbook/countries/australia/) and create a dictionary with data containing the following types: float, string, integer, list, and dict.
- Choose any data you wish.
- To confirm, you should have a dictionary that you identified via a key.

In [ ]:
# Please write your code here!

#### 5.2.3. Common `dict` Functionality

- We can do some common things with dicts.
- We will demonstrate them with examples below.

In [45]:
# number of key-value pairs in a dict

len(china_data)

5

In [46]:
# get a list of all the keys

list(china_data.keys())

['country', 'year', 'GDP', 'population', 'unemployment']

In [47]:
# get a list of all the values

list(china_data.values())

['China', 2015, 11.06, 1.371, 4.051]

In [48]:
more_china_data = {"irrigated_land": 690_070, "top_religions": {"buddhist": 18.2, "christian" : 5.1, "muslim": 1.8}}

# Add all key-value pairs in mydict2 to mydict.
# if the key already appears in mydict, overwrite the
# value with the value in mydict2
china_data.update(more_china_data)
china_data

{'country': 'China',
 'year': 2015,
 'GDP': 11.06,
 'population': 1.371,
 'unemployment': 4.051,
 'irrigated_land': 690070,
 'top_religions': {'buddhist': 18.2, 'christian': 5.1, 'muslim': 1.8}}

In [49]:
# Get the value associated with a key or return a default value
# use this to avoid the NameError we saw above if you have a reasonable
# default value
china_data.get("irrigated_land", "Data Not Available")

690070

In [51]:
china_data.get("death_rate", "Data Not Available") # print "Data Not Available" if there is no key named "death_rate"

'Data Not Available'

**[Exercise]**
- Use Jupyter’s help facilities to learn how to use the `pop` method to remove the key `"irrigated_land"` (and its value) from the dict.

In [ ]:
china_data.pop()

**[Exercise]**
- Explain what happens to the value you popped.
- Experiment with calling `pop` twice.

In [ ]:
# Please write your code here!

### **5.3. Sets**

- Python has an additional way to represent collections of items: **sets**.
- Sets come up infrequently, but you should be aware of them.
- If you are familiar with the mathematical concept of sets, then you will understand the majority of Python sets already.
- If you don’t know the math behind sets, don’t worry: we’ll cover the basics of Python’s sets here.
- A set is **an unordered collection of unique elements**.
- The syntax for creating a set uses curly bracket `{` and `}`.
```python
{item1, item2, ..., itemN}
````

- Here is an example.

In [52]:
s = {1, "hello", 3.0}
print("s has type", type(s))
s

s has type <class 'set'>

{1, 3.0, 'hello'}

**[Exercise]**
- Try creating a set with repeated elements (e.g. {1, 2, 1, 2, 1, 2}).
- What happens?
- Why?

In [ ]:
# Please write your code here!

- As with lists and tuples, we can check if something is in the set and check the set’s length:

In [53]:
print("len(s) =", len(s))
"hello" in s

len(s) = 3

True

- Unlike lists and tuples, we can’t extract elements of a set `s` using `s[N]` where N is a number.

In [54]:
s[1]

TypeError: ignored

- This is because sets are **not ordered**, so the notion of getting the second element (`s[1]`) is not well defined.
- We add elements to a set `s` using `s.add`.

In [55]:
s.add(100)
s

{1, 100, 3.0, 'hello'}

In [56]:
s.add("hello") # nothing happens, why?
s

{1, 100, 3.0, 'hello'}

- We can also do **set operations**.
- Consider the set s from above and the set s2 = {"hello", "world"}.
    - `s.union(s2)`: returns a set with all elements in either s or s2 (합집합)
    - `s.intersection(s2)`: returns a set with all elements in both s and s2 (교집합)
    - `s.difference(s2)`: returns a set with all elements in s that aren’t in s2 (차집합)
    - `s.symmetric_difference(s2)`: returns a set with all elements in only one of s and s2 (대칭차집합)

**[Exercise]**
- Test out two of the operations described above using the original set we created, `s`, and the set created below `s2`.

In [ ]:
s2 = {"hello", "world"}

In [ ]:
# Operation 1; Please write your code here!

In [ ]:
# Operation 2; Please write your code here!

- As with tuples and lists, a set function can convert other collections to sets.

In [57]:
x = [1, 2, 3, 1]
set(x)

{1, 2, 3}

In [58]:
t = (1, 2, 3, 1)
set(t)

{1, 2, 3}

- Likewise, we can convert sets to lists and tuples.

In [60]:
list(s)

[100, 1, 3.0, 'hello']

In [59]:
tuple(s)

(100, 1, 3.0, 'hello')

---

## **6. Control Flow**

### **6.1. Net Present Values and Asset Pricing**

- In **`6.3`**, we’ll introduce two related topics from economics:
    - Net present valuations
    - Asset pricing
- These topics will motivate some of the programming we do in **`6.1`** and **`6.2`**.

#### 6.1.1. Discount Rate

- In economics and finance, **“assets” provide a stream of payoffs**.
- These “assets” can be concrete or abstract:
    - a stock pays dividends over time,
    - a bond pays interest,
    - an apple tree provides apples,
    - a job pays wages, and
    - an education provides possible jobs (which, in turn, pay wages).
- When **deciding the price to pay for an asset** or how to choose between different alternatives, we need to take into account that **most people would prefer to receive 1 today vs. 1 next year.**
- This reflection on consumer preferences leads to the notion of a **discount rate(할인율)**.
- If you are indifferent between receiving 1.00 today and 1.10 next year, then the discount rate over the next year is $r = 0.10$ (=10%).
- If we assume that an individuals preferences are consistent over time, then we can apply that same discount rate to valuing assets further into the future.
    - For example, we would expect that the consumer would be indifferent between consuming 1.00 today and $(1+r)(1+r)=1.21$ dollars two years from now (i.e. discount twice).
- Inverting this formula, 1 delivered two years from now is equivalent to $\frac{1}{(1+r)^2}$ today. (2년 후의 1의 가치와 현재의 $\frac{1}{(1+r)^2}$의 가치가 동일하다.)

**[Exercise]**
- Government bonds are often issued as **zero-coupon bonds(무이표채)**, meaning that they make no payments throughout the entire time that they are held, but, rather make a single payment at the time of maturity.
- How much should you be willing to pay for a zero-coupon bond that paid 100 in 10 years with an interest rate of 5%?

In [ ]:
# Please write your code here!

#### 6.1.2. Net Present Value

- If an asset pays a stream of payoffs over multiple time periods, then we can use a discount rate to calculate the value to the consumer of a entire sequence of payoffs.
- Most generally, we enumerate each discrete time period (e.g. year, month, day) by the index $t$ where today is $t=0$ and the asset lives for $T$ periods.
- List the payoff at each time period as $y_t$, which we will assume, for now, is known in advance.
- Then if the discount factor is $r \ge 0$, the consumer “values” the payoff $y_t$ delivered at time $t$ as $\frac{1}{(1+r)^t}y_t$ where we note that if
$t = 0$, the value is just the current payoff $y_0$.

- Using this logic, we can write an expression for the value of the entire sequence of payoffs with a sum.

$$ P_0 = \sum^{T}_{t=0} \left( \frac{1}{1+r} \right)^t y_t \tag{1}$$

- If $y_t$ is a constant, then we can compute this sum with a simple formula!
- Below, we present some useful formulas that come from infinite series that we will use to get our net present value formula. ($y_t$가 상수이면 $y_t$가 시그마 밖으로 빠져나가게 되고, 결국 등비급수의 합을 구하는 문제가 된다.)
- For any constant $0 < \beta < 1$ and integer value $\tau > 0$,

$$ \sum^{∞}_{t=0} \beta^t = \frac{1}{1-\beta} $$

$$ \sum^{\tau}_{t=0} \beta^t = \frac{1-\beta^{\tau+1}}{1-\beta} \tag{2}$$

$$ \sum^{∞}_{t=\tau} \beta^t = \frac{\beta^{\tau}}{1-\beta} $$

- In the case of an asset which pays one dollar until time $T$, we can use these formulas, taking $\beta = \frac{1}{1+r}$ and $T=\tau$, to find

$$ P_0 = \sum^{\tau}_{t=0} \left( \frac{1}{1+r} \right)^t = \frac{1-(\frac{1}{1+r})^{\tau+1}}{1-\frac{1}{1+r}} = \frac{1+r}{r} - \frac{1}{r} \left(\frac{1}{1+r}\right)^{\tau} $$

- Note that we can also consider an asset that lives and pays forever if $T=∞$
, and from (2), the value of an asset which pays 1 forever is $\frac{1+r}{r}$.

### **6.2. Conditionals**

#### 6.2.1. `if` or `if-else`

- Sometimes, we will only want to execute some piece of code if a certain condition is met.
- These conditions can be anything.
    - For example, we might add to total sales if the transaction value is positive, but add to total returns if the value is negative.
    - Or, we might want to add up all incurred costs, only if the transaction happened before a certain date.
- We use conditionals **to run particular pieces of code when certain criterion are met**. (즉 **조건(condition)이 참일 때 그 아래 코드조각을 실행한다.**)
- **Conditionals are closely tied to booleans**, so if you don’t remember what those are, go back to **`3`** for a refresher.
- The basic syntax for conditionals is
```python
if condition:
    # code to run when condition is True
else:
    # code to run if no conditions above are True
```

- Note that immediately following the condition, **there is a colon(`:`)** and that the next line begins with blank spaces (which are called indentation).
- **Using 4 spaces is a very strong convention for indentation**, so that is what we do — we recommend that you do the same.
- Also note that the `else` clause is optional.
- Let’s see some simple examples.

In [ ]:
if True:
    print("This is where `True` code is run")

This is where `True` code is run

- The example below is equivalent to just typing the print statement.

In [ ]:
if 1 < 2:
     print("This is where `True` code is run")

This is where `True` code is run

- Now, it is not equivalent to just typing the print statement.

In [ ]:
if False:
    print("This is where `True` code is run") # 조건이 거짓(False)이기 때문에 아래의 코드를 무시하고 넘어간다. 즉 여기선 아무것도 출력되지 않는다.

In [ ]:
if 1 > 2:
     print("This is where `True` code is run") # 위와 마찬가지로 `1 > 2`는 거짓이므로 같은 결과이다.

- Notice that when you run the cells above nothing is printed.
- That is because **the condition for the if statement was not true, so the code inside the indented block was never run.**
- This also allows us to demonstrate the role of indentation in determining the “block” of code.

In [ ]:
val = False

if val is True: # check an expression
    print("This is where `True` code is run")
    print("More code in the if block")
print("Code runs after 'if' block, regardless of val") # 들여쓰기가 되어있지 않기때문에 조건문과는 상관이 없다. 따라서 조건문이 먼저 실행된 후 들여쓰기가 되지 않은 부분으로 넘어간다.

**[Exercise]**
- Run the following two variations on the code with only a single change in the indentation.
- After, modify the `x` to print `3` and then `2`, `3` instead.

In [ ]:
x = 1

if x > 0:
    print("1")
    print("2")
print("3")

1
2
3

In [ ]:
x = 1

if x > 0:
    print("1")
print("2") # changed the indentation
print("3")

1
2
3

- The next example shows us how `else` works.

In [ ]:
val = (2 == 4)  # returns False

if val is True:
    print("This is where `True` code is run")
else:
    print("This is where `False` code is run")
    print("More else code")

print("Code runs after 'if' block, regardless of val")

This is where `False` code is run
More else code
Code runs after 'if' block, regardless of val

- The `if False: ...` part of this example is the same as the example before, but now, we added an `else:` clause.
- In this case, **because the conditional for the `if` statement was not `True`, the if code block was not executed, but the `else` block was.**
- Finally, the `Condition is True` is assumed in the `if` statement, and is often left out.
- For example, the following are identical:

In [ ]:
if (1 < 2) is True:
    print("1 < 2")

if 1 < 2:
    print("1 < 2")

1 < 2
1 < 2

**[Exercise]**
- Using the code cell below as a start, print `"Good afternoon"` if the `current_time` is past noon.
- Otherwise, do nothing.

**[Hint]**
- Write some conditional based on `current_time.hour`.

In [ ]:
import datetime
current_time = datetime.datetime.now()

## Please write your code here!

**[Exercise]**
- In this example, you will generate a random number between 0 and 1 and then display “x > 0.5” or “x < 0.5” depending on the value of the number.
- This also introduces a new package `numpy.random` for drawing random numbers (2주차에 더 자세히 다룰 예정입니다.).

In [ ]:
import numpy as np
x = np.random.random() # 0부터 1 사이의 난수 하나를 `x`에 할당합니다.
print(f"x = {x}")

## Please write your code here!

#### 6.2.2. `if-elif-else`

- Sometimes, you have more than one condition you want to check.
    - For example, you might want to run a different set of code based on which quarter a particular transaction took place in.
    - In this case you could check whether the date is in Q1(1분기), or in Q2(2분기), or in Q3(3분기), or if not any of these it must be in Q4(4분기).
- The way to express this type of conditional is to use one or more `elif` clause in addition to the `if` and the `else`.
- The syntax is:
```python
if condition1:
    # code to run when condition1 is True
elif condition2:
    # code to run when condition2 is True
elif condition3:
    # code to run when condition3 is True
else:
    # code to run when none of the above are true
```

- You can **include as many `elif` clauses as you want**.
- As before, the **`else` part is optional**.
- Here’s how we might express the quarter example referred to above.

In [ ]:
import datetime
halloween = datetime.date(2017, 10, 31) # 할로윈 날짜를 변수에 할당합니다.

if halloween.month > 9:
    print("Halloween is in Q4")
elif halloween.month > 6:
    print("Halloween is in Q3")
elif halloween.month > 3:
    print("Halloween is in Q2")
else:
    print("Halloween is in Q1")

Halloween is in Q4

- Note that when there are multiple `if` or `elif` conditions, **only the code corresponding to the first true clause is run**. (가장 먼저 조건이 참인 코드블럭만 실행 후 해당 `if-elif-else` 문의 나머지 코드블럭은 무시하고 넘어간다.)
- We saw this in action above.
    - We know that when `halloween.month > 9` is true, then **`halloween.month > 6` and `alloween.month > 3` must also be true, but only the code block associated with `halloween.month > 9` was printed.**

### **6.3. Iterations**

- When doing computations or analyzing data, we often need to **repeat certain operations a finite number of times** or **until some condition is met**.
- Examples include:
    - processing all data files in a directory (folder),
    - aggregating revenues and costs for every period in a year, or
    - computing the net present value of certain assets.
- These are all examples of a programming concept called **iteration**.
- We feel the concept is best understood through example, so we will present a contrived example and then discuss the details behind doing iteration in Python.

#### 6.3.1. A Contrived Example

- Suppose we wanted to print out the first 10 integers and their squares.
- We could do something like this.

In [ ]:
print(f"1**2 = {1**2}")
print(f"2**2 = {2**2}")
print(f"3**2 = {3**2}")
print(f"4**2 = {4**2}")
# .. and so on until 10

1**2 = 1
2**2 = 4
3**2 = 9
4**2 = 16

- As you can see, the code above is repetitive.
- For each integer, the code is exactly the same except for the two places where the “current” integer appears.
- Suppose that I asked you to write the same print statement for an int stored in a variable named `i`.
- You might write the following code:
```python
print(f"{i}**2 = {i**2}")
```

- This more general version of the operation suggests a strategy for achieving our goal with less repetition of code:
    - have a variable `i` take on the values 1 through 10 (Quiz: How can we use `range` to create the numbers 1 to 10? Answer: `range(1, 11)`) and run the line of code above for each new value of i.
- This can be accomplished with a `for` loop!

In [ ]:
for i in range(1, 11):
     print(f"{i}**2 = {i**2}")

1**2 = 1
2**2 = 4
3**2 = 9
4**2 = 16
5**2 = 25
6**2 = 36
7**2 = 49
8**2 = 64
9**2 = 81
10**2 = 100

- Whoa😮, what just happened?
- The integer `i` took on the values in `range(1, 11)` one by one and for each new value it did the operations in the indented block (here just one line that called the `print` function).

#### 6.3.2. `for` Loops

- The general structure of a standard `for` loop is as follows.
```python
for item in iterable:
        # operation 1 with item
        # operation 2 with item
        # ...
        # operation N with item
```

- `iterable` is anything capable of producing one item at a time (see [here](https://docs.python.org/3/glossary.html#term-iterable) for official definition from the Python team).
- We’ve actually already seen some of the most common iterables!
    - Lists, tuples, dicts, and range/zip/enumerate objects are all iterables.
- Note that we can have as many operations as we want inside the indented block.
- We will **refer to the indented block as the “body” of the loop.**
- **When the for loop is executed, `item` will take on one value from `iterable` at a time and execute the loop body for each value.**

**[Exercise]**
- In economics, when **an individual has some knowledge, skills, or education which provides them with a source of future income**, we call it [human capital](https://en.wikipedia.org/wiki/Human_capital).
- When a student graduating from high school is considering whether to continue with post-secondary education, they may consider that it gives them higher paying jobs in the future, but requires that they don’t begin working until after graduation.
- Consider the simplified example where a student has perfectly forecastable employment and is given two choices:
    1. Begin working immediately and make 40,000 a year until they retire 40 years later.
    2. Pay 5,000 a year for the next 4 years to attend university, then get a job paying 50,000 a year until they retire 40 years after making the college attendance decision.
- Should the student enroll in school if the discount rate is $r = 0.05$?

In [ ]:
# Discount rate
r = 0.05

# High school wage
w_hs = 40_000

# College wage and cost of college
c_college = 5_000
w_college = 50_000

# Compute npv of being a hs worker; Please write your code here!


# Compute npv of attending college; Please write your code here!


# Compute npv of being a college worker; Please write your code here!


# Is npv_collegeworker - npv_collegecost > npv_hsworker; Please write your code here!

- When iterating, each `item` in `iterable` might actually contain more than one value.
- Recall that tuples (and lists) can be unpacked directly into variables.

In [ ]:
tup = (4, "test")
i, x = tup
print(f"i = {i}, x = {x}, tup = {tup}")

i = 4, x = test, tup = (4, 'test')

- Also, recall that the value of a `enumerate(iterable)` is a tuple of the form `(i, x)` where `iterable[i] == x`.
- When we use `enumerate` in a for loop, we can “unpack” both values at the same time as follows:

In [ ]:
# revenue by quarter
company_revenue = [5.12, 5.20, 5.50, 6.50]

for index, value in enumerate(company_revenue):
    print(f"quarter {index} revenue is ${value} million")

quarter 0 revenue is $5.12 million
quarter 1 revenue is $5.2 million
quarter 2 revenue is $5.5 million
quarter 3 revenue is $6.5 million

- Similarly, the index can be used to access another vector.

In [ ]:
cities = ["Phoenix", "Austin", "San Diego", "New York"]
states = ["Arizona", "Texas", "California", "New York"]

for index, city in enumerate(cities):
    state = states[index]
    print(f"{city} is in {state}")

Phoenix is in Arizona
Austin is in Texas
San Diego is in California
New York is in New York

**[Exercise]**
- Instead of the above, write a for loop that uses the lists of cities and states below to print the same “{city} is in {state}” using a `zip()` instead of an `enumerate()`.

In [ ]:
cities = ["Phoenix", "Austin", "San Diego", "New York"]
states = ["Arizona", "Texas", "California", "New York"]

# Please write your code here!

#### 6.3.3. `while` Loops

- A related but slightly different form of iteration is to **repeat something until some condition is met.**
- This is typically achieved using a `while` loop.
- The structure of a while loop is:
```python
while True_condition:
    # repeat these steps
```
- `True_condition` is some conditional statement that should **evaluate to True when iterations should continue and False when Python should stop iterating**.
- For example, suppose we wanted to know the smallest N such that $\sum\limits^N_{i=0}i > 1000$.
- We figure this out using a while loop as follows.

In [ ]:
total = 0
i = 0
while total <= 1000:
    i = i + 1
    total = total + i

print("The answer is", i)

The answer is 45

- Let’s check our work. (검산)

In [ ]:
# Should be just less than 1000 because range(45) goes from 0 to 44
sum(range(45))

990

In [ ]:
# should be between 990 + 45 = 1035
sum(range(46))

1035

- A warning: one common programming error with while loops is to forget to **set the variable you use in the condition prior to executing**.
- For example, take the following code which correctly sets a counter.

In [ ]:
i = 0

- And then executes a while loop

In [ ]:
while i < 3:
    print(i)
    i = i + 1
print("done")

0
1
2
done

- No problems.
- But if you were to execute the above cell again, or another cell, the `i = 3` remains, and code is never executed (since `i < 3` begins as False).

**[Exercise]**
- Companies often invest in training their employees to raise their productivity.
- Economists sometimes wonder why companies spend this money when this incentivizes other companies to hire their employees away with higher salaries since employees gain human capital from training?
- Let’s say that it costs a company 25,000 dollars to teach their employees Python, but it raises their output by 2,500 per month.
- How many months would an employee need to stay for the company to find it profitable to pay for their employees to learn Python if their discount rate is r = 0.01?

In [ ]:
# Define cost of teaching python
cost = 25_000
r = 0.01

# Per month value
added_value = 2500

n_months = 0
total_npv = 0.0

# Put condition below here: 아래를 잘보고 코드를 수정해주세요.
while False: # (replace False with your condition here)
    n_months = n_months + 1  # Increment how many months they've worked

    # Increase total_npv

#### 6.3.4. `break` and `continue`

- Sometimes we want to stop a loop early if some condition is met.
- Let’s revisit the example of finding the smallest N such that $\sum\limits^N_{i=0}i > 1000$.
- Clearly `N` must be less than 1000, so we know we will find the answer if we start with a for loop over all items in `range(1001)`.
- Then, we can keep a running total as we proceed and tell Python to stop iterating through our range once total goes above 1000.

In [ ]:
total = 0
for i in range(1001):
    total = total + i
    if total > 1000:
        break

print("The answer is", i)

The answer is 45

**[Exercise]**
- Try to find the index of the first value in `x` that is greater than 0.999 using a for loop and `break`.

**[Hint]**
- Try iterating over range(len(x)).

In [ ]:
x = np.random.rand(10_000)
# Please write your code here

- Sometimes we might want to **stop the body of a loop early if a condition is met.**
- To do this we can use the `continue` keyword.
- The basic syntax for doing this is:
```python
for item in iterable:
      # always do these operations
      if condition:
          continue

      # only do these operations if condition is False
```

- Inside the loop body, Python will **stop that loop iteration of the loop and continue directly to the next iteration** when it encounters the `continue ` statement.
- For example, suppose I ask you to loop over the numbers 1 to 10 and print out the message “{i} An odd number!” whenever the number `i` is odd, and do nothing otherwise.
- You can use `continue` to do this as follows:

In [ ]:
for i in range(1, 11):
    if i % 2 == 0:  # an even number... This is modulus division
        continue

    print(i, "is an odd number!")

1 is an odd number!
3 is an odd number!
5 is an odd number!
7 is an odd number!
9 is an odd number!

**[Exercise]**
- Write a for loop that adds up all values in `x` that are greater than or equal to 0.5.
- Use the `continue` word to end the body of the loop early for all values of `x` that are less than 0.5.

**[Hint]**
- Try starting your loop with for value in `x`: instead of iterating over the indices of `x`.

In [ ]:
x = np.random.rand(10_000)

# Please write your code here!

#### 6.3.5. Comprehension

- Often, we will want to **perform a very simple operation for every element of some iterable** and **create a new iterable** with these values.
- This could be done by writing a for loop and saving each value, but often using what is called a **comprehension** is more readable.
- Like many Python concepts, a comprehension is easiest to understand through example.
- Imagine that we have a list `x` with a list of numbers.
    - We would like to create a list `x2` which has the squared values of `x`.

In [ ]:
x = list(range(4)) # a list of numbers

# [Solution 1] Create squared values with a loop
x2_loop = []
for x_val in x:
    x2_loop.append(x_val**2)

# [Solution 2] Create squared values with a comprehension
x2_comp = [x_val**2 for x_val in x]

print(x2_loop)
print(x2_comp)

[0, 1, 4, 9]
[0, 1, 4, 9]

- Notice that much of the same text appears when we do the operation in the loop and when we do the operation with the comprehension.
- We need to specify what we are iterating over – in both cases, this is for `x_val` in `x`.
- We need to square each element `x_val**2`.
- It needs to be stored somewhere – **(Solution 1)** in `x2_loop`, this is done by appending each element to a list, and **(Solution 2)** in x2_comp, this is done automatically because the operation is enclosed in a list.
- **We can do comprehension with many different types of iterables**, so we demonstrate a few more below.

- **[Example]** 주식의 종목코드를 key로, 각 주식의 가격을 value로 하는 사전을 만든다.

In [ ]:
# Create a dictionary from lists

tickers = ["AAPL", "GOOGL", "TVIX"]
prices = [175.96, 1047.43, 8.38]

d = {key: value for key, value in zip(tickers, prices)}
d

{'AAPL': 175.96, 'GOOGL': 1047.43, 'TVIX': 8.38}

- **[Example]** 사전으로부터 각 기업의 본사 위치를 원소로 하는 리스트를 만든다.

In [ ]:
# Create a list from a dictionary
d = {"AMZN": "Seattle", "TVIX": "Zurich", "AAPL": "Cupertino"}

hq_cities = [d[ticker] for ticker in d.keys()]
hq_cities

['Seattle', 'Zurich', 'Cupertino']

- **[Example]** 0부터 10까지의 사인함수값의 리스트를 만든다.

In [ ]:
import math

# List from list
x = range(10)

sin_x = [math.sin(x_val) for x_val in x]
sin_x

[0.0,
 0.8414709848078965,
 0.9092974268256817,
 0.1411200080598672,
 -0.7568024953079282,
 -0.9589242746631385,
 -0.27941549819892586,
 0.6569865987187891,
 0.9893582466233818,
 0.4121184852417566]

**[Exercise]**
- Returning to our previous example: print “{city} is in {state}” for each combination using a `zip` and a comprehension.

In [ ]:
cities = ["Phoenix", "Austin", "San Diego", "New York"]
states = ["Arizona", "Texas", "California", "New York"]

# Please write your code here

- Finally, we can use this approach to build complicated nested dictionaries.

In [ ]:
gdp_data = [9.607, 10.48, 11.06]
years = [2013, 2014, 2015]
exports = [ {"manufacturing": 2.4, "agriculture": 1.5, "services": 0.5},
            {"manufacturing": 2.5, "agriculture": 1.4, "services": 0.9},
            {"manufacturing": 2.7, "agriculture": 1.4, "services": 1.5}]

# 위에 정의한 각각의 데이터를 합친다.
data = zip(years, gdp_data,exports)
data_dict = {year : {"gdp" : gdp, "exports": exports} for year, gdp, exports in data} # comprehension
print(data_dict)

# total exports by year
[data_dict[year]["exports"]["services"] for year in data_dict.keys()]

{2013: {'gdp': 9.607, 'exports': {'manufacturing': 2.4, 'agriculture': 1.5, 'services': 0.5}}, 2014: {'gdp': 10.48, 'exports': {'manufacturing': 2.5, 'agriculture': 1.4, 'services': 0.9}}, 2015: {'gdp': 11.06, 'exports': {'manufacturing': 2.7, 'agriculture': 1.4, 'services': 1.5}}}

[0.5, 0.9, 1.5]

---

## **7. Functions**

### **7.1. Application : Production Functions**

- Production functions are useful when modeling the economics of firms producing goods or the aggregate output in an economy.
- Though the term 'function' is used in a mathematical sense here, we will be making tight connections between the programming of mathematical functions and Python functions.

#### 7.1.1. Factors of Production

- The factors of production are `the inputs used in the production of some sort of output`.
- Some example factors of production include :
  - physical capital, e.g. machines, buildings, computers, and power stations.
  - labor, e.g. all of the hours of work from different types of employees of a firm.
  - human capital, e.g. the knowledge of employees within a firm.
- A production function maps a set of inputs to the output, e.g. the amount of wheat produced by a farm, or widgets produced in a factory.

- As an example of the notation, we denote the total units of labor and physical capital used in a factory as well as $L$ and $K$ respectively.
- If we denote the physical output of the factory as $Y$, then a production function $F$ that transforms labor and capital into output might have the form :
$$ Y = F(K, L) $$

#### 7.1.2. An Example of Production Function

- Throughout this note, we will use `Cobb-Douglas` production function to help us understand how to create Python functions and why they are useful.
- The Cobb-Douglas production function has appealing statistical properties when brought to data.
- This function is displayed below.
$$ Y = zK^{\alpha}L^{1 - \alpha} $$
- The function is parameterized by :
  - A parameter $\alpha \in [0, 1]$, called `the output elasticity of capital`.
  - A value $z$ called the `Total Factor Productivity (TFP)`.

### **7.2. What are Functions of Python?**

- We like to think of a function as a production line in a manufacturing plant : we pass zero or more things to it, operations take place in a set linear sequence, and zero or more things come out.
- We use functions for the following purposes :
  - **Re-usability** : Writing code to do a specific task just once, and reuse the code by calling the function.
  - **Organization** : Keep the code for distinct operations separated and organized.
  - **Sharing/Collaboration** : Sharing code across multiple projects or sharing pieces of code with collaborators.

### **7.3. How to Define Functions (of Python)**

- The basic syntax to create our own function is as follows:
```python
def function_name(inputs):
    '''
    steps of operations
    '''
    return outputs
```

- Here we see two new keywords : `def` and `return`.
  - `def` is used to tell Python we would like to define a new function.
  - `return` is used to tell Python what we would like to return from a function.

In [ ]:
def mean(numbers):
    total = sum(numbers)
    N = len(numbers)
    answer = total / N

    return answer

In [ ]:
x = [1, 2, 3, 4]
the_mean = mean(x)
the_mean

2.5

- `Indentation controls blocks of code` (along with the `scope` rules).

In [ ]:
def f():
    print(1)
    print(2)
f()

1
2

In [ ]:
def g():
    print(1)
print(2)
g()

2
1

#### 7.3.1. Scope

- In Python, functions define their own scope for variables.
- This is a programming concept called `variable scope`.
  - This means that `regardless of what name we give an input variable, the input will always referred to as the name inside the body of the function`.
  - It also means that `regardless of what name we give an output inside of the function, that this variable name was only valid inside of our function`.
  - Another point to make here is that `the intermediate variables we defined inside the function are only defined inside of the function - we cannot access them from outside`.
    - This point can be taken even further : `the same name can be bound to variables inside of blocks of code and in the outer scope`.

In [ ]:
x = 4
print(f"x = {x}")

def f():
    x = 5 # A different "x"
    print(f"x = {x}")

f() # calls function
print(f"x = {x}")

x = 4
x = 5
x = 4

- The final point we want to make about scope is that `function inputs and output don't have to be given a name outside the function`.

In [ ]:
mean([10, 20, 30])

20.0

- Note that we didn't name the input or the output, but the function was called successfully.

- Now, let's define a Cobb-Douglas production function where parameter $z = 1$ and $\alpha = 0.33$ and takes inputs $K$ and $L$.

In [ ]:
def cobb_douglas(K, L):
    z = 1
    alpha = 0.33

    return z * (K ** alpha) * (L ** (1 - alpha))

In [ ]:
cobb_douglas(1.0, 0.5)

0.6285066872609142

#### 7.3.2. Re-using Functions

- Economists are often intereested in this question : `how much does output change if we modify our inputs?`
- For example, take a production function $Y_1 = F(K_1, L_1)$ which produces $Y_1$ units of the goods.
  - If we then multiply the inputs each by $\gamma$, so that $K_2 = \gamma K_1$ and $L_2 = \gamma L_1$, then the output is $Y_2 = F(K_2, L_2) = F(\gamma K, \gamma L_2)$.
  - How does $Y_1$ compare to $Y_2$?

- Answering this question involves something called `returns to scale`.
  - Retruns to scale tells us whether our inputs are more or less productive as we have more of them.
- If, for any $K$, $L$, we multiply $K$, $L$ by a value $\gamma$ then
  - If $ \frac{Y_2}{Y_1} < \gamma $ then we say the production function has **decreasing returns to scale**.

  - If $ \frac{Y_2}{Y_1} = \gamma $ then we say the production function has **constant returns to scale**.
  
  - If $ \frac{Y_2}{Y_1} > \gamma $ then we say the production function has **increasing returns to scale**.

In [ ]:
y1 = cobb_douglas(1.0, 0.5)
print(y1)

y2 = cobb_douglas(2 * 1.0, 2 * 0.5)
print(y2)

0.6285066872609142
1.2570133745218284

In [ ]:
y2 / y1

2.0

- The production function has constant returns to scale.
- The following is an example of how writing functions can allow us to re-use code in ways we might not originally anticipate.

In [ ]:
def returns_to_scale(K, L, gamma):
    y1 = cobb_douglas(K, L)
    y2 = cobb_douglas(gamma * K, gamma * L)

    y_ratio = y2 / y1

    return y_ratio / gamma

In [ ]:
returns_to_scale(1.0, 0.5, 2.0)

1.0

---

**[Exercise]**
- What happens if we try different inputs in our Cobb-Douglas production function?

In [ ]:
returns_to_scale(3.0, 2.0, 3)

1.0

`[Answer]` Write the answer using comments.

In [ ]:
# Please write your code here!

---

- It turns out that with a little bit of algebra, we can check that this will always hold for our Cobb-Douglas example above.
- To show this, take an arbitrary $K$, $L$ and multiply the inputs by an arbitrary $\gamma$

$$ F(\gamma K, \gamma L) = z(\gamma K)^{\alpha} (\gamma L)^{1 - \alpha} = z\gamma^{\alpha} K^{\alpha} \gamma^{1 - \alpha} L^{1 - \alpha} = \gamma z K^{\alpha} L^{1 - \alpha} = \gamma F(K, L)$$

- For an example of a production function that is not CRS, look at a generalization of the Cobb-Douglas production function that has different `output elasticities` for the 2 inputs.

$$ Y = zK^{\alpha_1}L^{\alpha_2} $$
- Note that if $ \alpha_2 = 1 - \alpha_1 $, this is our Cobb-Douglas production function.

---

**[Exercise]**
- Define a function named `var` that takes a list (call it `x`) and computes the variance.
- This function should use the mean function that we defined earlier.

In [ ]:
# Please write your code here!

---

#### 7.3.3. Multiple Returns

- Another valuable element to analyze on production functions is how output changes as we change only one of the inputs.
- We will call this the `marginal product`.
- For example, compare the output using $K$, $L$ units of input to that with and $\epsilon$ units of labor.
- Then the marginal product of labor (MPL) is defined as :
$$ \frac{F(K, L+\epsilon) - F(K, L)}{\epsilon} $$

- This tells us how much additional output is created relative to the additional input.
- If the input can be divided into small units, then we can use calculus to take this limit, using the partial derivative of the production function relative to that input.
- In this case, we define the marginal product of labor (MPL) and marginal product of capital (MPK) as :

$$ MPL(K, L) = \frac{\partial F(K, L)}{\partial L} $$

$$ MPL(K, L) = \frac{\partial F(K, L)}{\partial K} $$

- In the Cobb-Douglas example above, this becomes :

$$ MPK(K, L) = z \alpha \left( \frac{K}{L} \right)^{\alpha - 1} $$

$$ MPK(K, L) = z (1 - \alpha) \left( \frac{K}{L} \right)^{\alpha} $$

- Let's test it out with Python.
- The syntax for a return statement with multiple items is `return item1, item2, ..., itemN`.

In [ ]:
def marginal_products(K, L, epsilon):
    mpl = (cobb_douglas(K, L + epsilon) - cobb_douglas(K, L)) / epsilon
    mpk = (cobb_douglas(K + epsilon, L) - cobb_douglas(K, L)) / epsilon

    return mpl, mpk

In [ ]:
tup = marginal_products(1.0, 0.5, 1e-4)
print(tup)

(0.8421711708284096, 0.20740025904131265)

- Instead of using the tuple, these can be `directly unpacked to variables`.

In [ ]:
mpl, mpk = marginal_products(1.0, 0.5, 1e-4)

print(f"mpl = {mpl}, mpk = {mpk}")

mpl = 0.8421711708284096, mpk = 0.20740025904131265

- We can use this to calculate the marginal products for different `K`, fixing `L` using a comprehension.

In [ ]:
Ks = [1.0, 2.0, 3.0]

[marginal_products(K, 0.5, 1e-4) for K in Ks]

[(0.8421711708284096, 0.20740025904131265),
 (1.058620425367085, 0.13035463304111872),
 (1.2101811517950534, 0.09934539767386674)]

#### 7.3.4. Documentation

- To provide useful information of function to users, we need to add whta Python programmers call a `docstring` to our functions.
- This is done by putting a string (not assigned to any variable name) as the first line of the body of the function (after the line with `def`).

```python
def function_name(inputs):
    """
    docstring
    """
    # operations
    return outputs
```

- Let's re-define our `cobb_douglas` function to include a docstring.

In [ ]:
def cobb_douglas(K, L):
    """
    Computes the production F(K, L) for a Cobb-Douglas production function

    Takes the form F(K, L) = z K^{alpha} L^{1 - alpha}

    We restrict z = 1 and alpha = 0.33
    """
    return 1.0 * K**(0.33) * L**(1.0 - 0.33)

- Now when we have Jupyter evaluate `cobb_douglas?`, our `message is displayed` (or `use the Contextual Help window` with `Jupyterlab` and `Ctrl-I` or `Cmd-I`).

In [ ]:
cobb_douglas?

Signature: cobb_douglas(K, L)
Docstring:
Computes the production F(K, L) for a Cobb-Douglas production function

Takes the form F(K, L) = z K^{alpha} L^{1 - alpha}

We restrict z = 1 and alpha = 0.33
File:      c:\users\seho6\appdata\local\temp\ipykernel_27964\3693588049.py
Type:      function

- We recommend that you `always include at least a very simple docstring` for nontrivial functions.

---

**[Exercise]**
- Redefine the returns_to_scale function and add a docstring.
- Confirm that it works by running the cell containing returns_to_scale? below.
- **[Note]** You do not need to change the actual code in the function — just copy/paste and add a docstring in the correct line.

In [ ]:
# re-define the `returns_to_scale` function here

In [ ]:
# test it here

returns_to_scale?

---

#### 7.3.5. Default and Keyword Arguments

- Functions can have optional arguments.
- To accomplish this, these arguments must have a default value by saying `name=default_value` instead of just `name` as we list the arguments.

In [ ]:
def cobb_douglas(K, L, alpha = 0.33, z = 1):
    """
    Computes the production F(K, L) for a Cobb-Douglas production function

    Takes the form F(K, L) = z K^{\alpha} L^{1 - \alpha}
    """
    return z * K**(alpha) * L**(1.0 - alpha)

- We can now call this function by passing in just K and L.

In [ ]:
cobb_douglas(1.0, 0.5)

0.6285066872609142

- However, we can also set the other arguments of the function by passing more than just K and L.

In [ ]:
cobb_douglas(1.0, 0.5, 0.35, 1.6)

1.0196485018554098

- In the example above, we used `alpha = 0.35, z = 1.6`.

- We can also refer to function arguments by their name, instead of ontly their position (order).
- To do this, we would write `func_name(arg=value)` for as many of the arguments as we want.

In [ ]:
cobb_douglas(1.0, 0.5, z = 1.5)

0.9427600308913713

**[Exercise]**
- Experiment with the `sep` and `end` arguments to the print function.
- These can only be set by name.

In [ ]:
print("Hello", "World", sep="@", end=".")

Hello@World.

- In terms of variable scope, the `z` name within the function is different from any other `z` in the outer space.

In [ ]:
x = 5

def f(x):
    return x

f(x) # coincidence it has the same name.

5

In [ ]:
z = 1.5

cobb_douglas(1.0, 0.5, z=z) # no problem

0.9427600308913713

- In that example, the `z` on the left hand side of `z = z` refers to the local variable name in the function whereas the `z` on the right hand side refers to the `z` in the outer scope.

#### 7.3.6. Aside : Methods

- As we learned earlier, all variables in Python have a type associated with them.
- Different types of variables have different functions or opertaions defined for them.
- When certain functionality is closely tied to the type of an object, it is often implemented as a special kind of function known as a **method**.

- For now, you only need two things about methods :
  1. We call them by doing `variable.method_name(other_arguments)` instead of `function_name(variable, other_arguments)`.
  2. A method is a function, even though we vall it using a different notation.

In [ ]:
x = "This is my handy string!"

x.upper()

'THIS IS MY HANDY STRING!'

In [ ]:
x.title()

'This Is My Handy String!'

### **7.4. More on Scope**

- The same concept applies to Python functions, where `the arguments are just placeholder names`.
- This is an appealing feature of functions for avoiding coding errors : `names of variables within the function are localized` and `won't clash with those on the outside`.
- Importantly, when Python looks for variables matching a particular name, `it begins in the most local scope`.

In [ ]:
def cobb_douglas2(K, L, alpha):

    z = 1

    return z * K**alpha * L**(1 - alpha)

print(cobb_douglas2(1.0, 0.5, 0.2))
print("Setting alpha, does the result change?")
alpha = 0.5
print(cobb_douglas2(1.0, 0.5, 0.2))

0.5743491774985174
Setting alpha, does the result change?
0.5743491774985174

- Note that having an alpha in the outer scope does not impact the local one.
- A crucial element of the above function is that the alpha variable was available in the local scope of the function.

In [ ]:
def cobb_douglas3(K, L):

    z = 1

    # there are no local alpha in scope!
    return z * K**alpha * L**(1 - alpha)

alpha = 0.2 # in the outer scope
print(f"alpha = {alpha} gives {cobb_douglas3(1.0, 0.5)}")
alpha = 0.3
print(f"alpha = {alpha} gives {cobb_douglas3(1.0, 0.5)}")

alpha = 0.2 gives 0.5743491774985174
alpha = 0.3 gives 0.6155722066724582

- We have removed the alpha function parameter as well as the local definition of alpha.

- The intuition of scoping does not apply only for the “global” vs. “function” naming of variables, `but also for nesting`.

In [ ]:
z = 1
def output_given_alpha(alpha):
    # Scoping logic:
    # 1. local function name doesn't clash with global one
    # 2. alpha comes from the function parameter
    # 3. z comes from the outer global scope
    def cobb_douglas(K, L):
        return z * K**alpha * L**(1 - alpha)

    # using this function
    return cobb_douglas(1.0, 0.5)

alpha = 100 # ignored
alphas = [0.2, 0.3, 0.5]
# comprehension variables also have local scope
# and don't clash with the alpha = 100
[output_given_alpha(alpha) for alpha in alphas]

[0.5743491774985174, 0.6155722066724582, 0.7071067811865476]

---

## **8. Object Oriented Programming**

- As demonstrated earlier, often we need to use other packages, such as `scipy`, `numpy`, or other domain specified packages.
- When you check the source code of these packages, you may see new keywords in the code, such as **class**.
    - What are classes and why do we use them?
- This is a new programming paradigm - **Object-Oriented Programming (OOP)** that is commonly used in **writing large programs or packages**.
- When writing a large program, OOP has a number of pluses:
    - it simplifies the code for better readability,
    - better describes the end goal of the project,
    - is reusable, and
    - reduces the number of potential bugs in the code.
- Given these features, you will see OOP in most of the standard packages in the field.

- Understanding its basics will help you write better code.
- This chapter introduces the basics of OOP, with emphasis on the core components: *object, class, and inheritance, and encapsulation etc*.
- **Python is a highly object-oriented programming language** and understanding these concepts will help you program with a minimum amount of headaches.

### **8.1. Introduction to OOP**

- So far, all the codes we have written belong to the category of **procedure-oriented programming (POP)**, which consists of a list of instructions to tell the computer what to do; these instructions are then organized into functions.
- The program is divided into **a collection of variables, data structures, and routines** to accomplish different tasks.
- Python is a multi-paradigm programming language, which means it supports different programming approach.

- One different way to program in Python is **object-oriented programming (OOP)**.
- The learning curve is steeper, but it is extremely very powerful and worth the time invested in mastering it.
- **[Note]** you do not have to use OOP when programming in Python.
    - You can still write very powerful programs using the POP.
    - That said, the **POP is good for simple and small programs, while the OOP is better suited for large programs**.

- Let us take a closer look at object-oriented programming.
- The object-oriented programming breaks the programming task into **objects**, which combine data (known as **attributes**) and behaviors/functions (known as **methods**).
- Therefore, there are two main components of the OOP: **class** and **object**.

- The class is a **blueprint to define a logical grouping of data and functions**.
- It provides a way to create data structures that model real-world entities.
    - For example, we can create a `People` class that contains the data such as name, age, and some behavior functions to print out ages and genders of a group of people.
- While class is the blueprint, an object is an `instance` of the class with actual values.
    - For example, a person named ‘Iron man’ with age 35.

- Put it another way, **a class is like a template** to define the needed information, and **an object is one specific copy that filled in the template**.
- Also, objects instantiated from the same class are **independent** from each other.
    - For example, if we have another person - ‘Batman’ with age 33, it can be instantiated from the `People` class, but it is an independent instance.
- Let us implement the above example in Python.
- Do not worry if you do not understand the syntax below; the next section provide more helpful examples.

In [ ]:
class People():
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def greet(self):
        print("Greetings, " + self.name)

In [ ]:
person1 = People(name = 'Iron Man', age = 35)
person1.greet()
print(person1.name)
print(person1.age)

Greetings, Iron Man
Iron Man
35

In [ ]:
person2 = People(name = 'Batman', age = 33)
person2.greet()
print(person2.name)
print(person2.age)

Greetings, Batman
Batman
33

- In the above code example, we first defined a class - `People`, with *name* and *age* as the data, and a method *greet*.
- We then initialized an object - `person1` with the specific name and age.
- We can clearly see that the *class* defines the whole structure, while the object is just an `instance` of the `class`.
- Later, we instantiated another object, `person2`.
- It is clear that `person1` and `person2` are independent with each other, though they are all instantiated from the same class.

- The concept of OOP is to create reusable code. There are three key principles of using OOP:
    - **Inheritance** - a way of creating new classes from existing class without modifying it.
    - **Encapsulation** - a way of hiding some of the private details of a class from other objects.
    - **Polymorphism** - a way of using common operation in different ways for different data input.
- With the above principles, there are many benefits of using OOP:
    - It provides a clear modular structure for programs that enhances code re-usability.
    - It provides a simple way to solve complex problems.
    - It helps define more abstract data types to model real-world scenarios.
    - It hides implementation details, leaving a clearly defined interface.
    - It combines data and operations.

- There are also other advantages to use OOP in a large project.
- We encourage you can search online to find out more.
- At this point, you may still not fully understand OOP’s advantages until you are involved in complex large projects.
- We will continue to learn more about OOP during the course of this book, and its usefulness will become apparent.

### **8.2. Class and Object**

- The previous section introduced the two main components of OOP:
    - **Class**, which is a blueprint used to define a logical grouping of data and functions, and
    - **Object**, which is an instance of the defined class with actual values.
- In this section, we will get into greater detail of both of these components.

#### 8.2.1. Class

- A **class** is a definition of the structure that we want.
- Similar to a function, it is defined as a block of code, starting with the `class` statement.
- The syntax of defining a class is:
```python
class ClassName(superclass):
        def __init__(self, arguments):
            # define or assign object attributes
        
        def other_methods(self, arguments):
            # body of the method
```

- **[Note]** the definition of a class is very similar to a function.
    - It needs to be instantiated first before you can use it.
    - For the class name, it is **standard convention to start with a capital letter**.

- The **superclass** is used when you want create a new class to **inherit** the attributes and methods from another already defined class.
    - We will talk more about **inheritance** in the next section.
- The **__init__** is one of the special methods in Python classes that is run as soon as an object of a class is instantiated (created).
- It **assigns initial values to the object** before it is ready to be used.
- Note the two underscores at the beginning and end of the `init`, indicating this is a special method reserved for special use in the language.
- In this `init` method, you can assign attributes directly when you create the object.

- The `other_methods` functions are used to define the instance methods that will be applied on the attributes, just like functions we discussed before.
- You may notice that there is a parameter `self` for defining this method in the class.
- Why? A class instance method must have this extra argument as the first argument when you define it.
- This particular argument refers to the object itself; conventionally, we use `self` to name it.
- Through this self parameter, instance methods can freely access attributes and other methods in the same object.
- When we define or call an instance method within a class, we need to use this `self` parameter.
- Let us see an example below.

- **[EXAMPLE]** Define a class named `Student`, with the attributes `sid` (student id), `name`, `gender`, `type` in the `init` method and a method called `say_name` to print out the student’s name. All the attributes will be passed in except `type`, which will have a value as ‘learning’.

In [ ]:
class Student():

    def __init__(self, sid, name, gender):
        self.sid = sid
        self.name = name
        self.gender = gender
        self.type = 'learning'

    def say_name(self):
        print("My name is " + self.name)

- From the above example, we can see this simple class contains all the necessary parts mentioned previously.
- The `__init__` method will initialize the attributes when we create an object.
- We need to pass in the initial value for `sid`, `name`, and `gender`, while the attribute `type` is a fixed value as “learning”.

- These attributes can be accessed by all the other methods defined in the class with `self.attribute`, for example, in the `say_name` method, we can use the `name` attribute with `self.name`.
- The methods defined in the class can be accessed and used in other different methods as well using `self.method`.
- Let us see the following example.

**[Exercise]**
- Add a method **report** that print not only the student name, but also the student id.
- The method will have another argument *score*, that will pass in a number between 0 - 100 as part of the report.

In [ ]:
class Student():

    def __init__(self, sid, name, gender):
        self.sid = sid
        self.name = name
        self.gender = gender
        self.type = 'learning'

    def say_name(self):
        print("My name is " + self.name)

    def report(self, score):
        # Please write your code here!

#### 8.2.2. Object

- As mentioned before, an **object** is an instance of the defined class with actual values.
- We can have **many instances of different values associated with the class**, and each of these instances will be i**ndependent with each other** as we saw previously.
- Also, after we create an object, and call this instance method from the object, we do not need to give value to the `self` parameter since Python automatically provides it.
- See the following example:

- **[Example]** Create two objects (“001”, “Susan”, “F”) and (“002”, “Mike”, “M”), and call the method *say_name*.

In [ ]:
student1 = Student("001", "Susan", "F")
student2 = Student("002", "Mike", "M")

student1.say_name()
student2.say_name()
print(student1.type)
print(student1.gender)

My name is Susan
My name is Mike
learning
F

- In the above code, we created two objects, `student1` and `student2`, with two different sets of values.
- Each object is an instance of the `Student` class and has a different set of attributes.
- Type `student1. + [TAB]` to see the defined attributes and methods.
- To get access to one attribute, type `object.attribute`, e.g., `student1.type`.
- In contrast, to call a method, you need the parentheses because you are calling a function, such as `student1.say_name()`.

**[Exercise]**
- Call method *report* for student1 and student2 with score 95 and 90 individually.

**[Note]**
- We do not need the “self” as an argument here.

In [ ]:
# Please write your code here!

- We can see both methods calling to print out the data associated with the two objects.
- **[Note]** the score value we passed in is only available to the method `report` (within the scope of this method).
- We can also see that the method `say_name` call in the `report` also works, as long as you call the method with the `self` in it.

#### 8.2.3. Class vs Instance Attributes

- The attributes we presented above are actually called **instance attributes**, which means that they are **only belong to a specific instance**; when you use them, you need to use the `self.attribute` within the class.
- There are another type of attributes called class attributes, which will be shared with all the instances created from this class.
- Let us see an example how to define and use a class attribute.

- **[Example]** Modify the `Student` class to add a class attribute `n`, which will record how many object we are creating. Also, add a method `num_instances` to print out the number.

In [ ]:
class Student():

    n_instances = 0

    def __init__(self, sid, name, gender):
        self.sid = sid
        self.name = name
        self.gender = gender
        self.type = 'learning'
        Student.n_instances += 1

    def say_name(self):
        print("My name is " + self.name)

    def report(self, score):
        self.say_name()
        print("My id is: " + self.sid)
        print("My score is: " + str(score))

    def num_instances(self):
        print(f'We have {Student.n_instances}-instance in total')

- In defining a class attribute, we must define it outside of all the other methods `without` using `self`.
- To use the class attributes, we use `ClassName.attribute`, which in this case is `Student.n`.
- This attribute will be shared with all the instances that are created from this class.
- Let us see the following code to show the idea.

In [ ]:
student1 = Student("001", "Susan", "F")
student1.num_instances()
student2 = Student("002", "Mike", "M")
student1.num_instances()
student2.num_instances()

We have 1-instance in total
We have 2-instance in total
We have 2-instance in total

- As before, we created two objects, the instance attribute `sid`, `name`, but `gender` only belongs to the specific object.
- For example, `student1.name` is “Susan” and `student2.name` is “Mike”.
- But when we print out the class attribute `Student.n_instances` after we created object `student2`, the one in the `student1` changes as well.
- This is the expectation we have for the class attribute because it is shared across all the created objects.

- Now that we understand the difference between class and instance, we are in good shape to use basic OOP in Python.
- Before we can take full advantage of OOP, we still need to understand the concept of inheritance, encapsulation and polymorphism.
- Let us start next section!

### **8.3. Inheritance, Encapsulation, and Polymorphism**

- We have already seen the modeling power of OOP using the class and object functions by combining data and methods.
- There are three more important concept,
    - **inheritance**, which makes the OOP code more modular, easier to reuse and build a relationship between classes.
    - **Encapsulation** can hide some of the private details of a class from other objects, while
    - **polymorphism** can allow us to use a common operation in different ways.
- In this section, we will briefly discuss them.

#### 8.3.1. Inheritance

- Inheritance allows us to define a class that inherits all the methods and attributes from another class.
- Convention denotes the new class as **child class**, and the one that it inherits from is called **parent class** or **superclass**.
- If we refer back to the definition of class structure, we can see the structure for basic inheritance is `class ClassName(superclass)`, which means the new class can access all the attributes and methods from the superclass.
- **Inheritance builds a relationship between the child class and parent class**, usually in a way that **the parent class is a general type** while **the child class is a specific type**.
- Let us try to see an example.

**[Example]**
- Define a class named `Sensor` with attributes `name`, `location`, and `record_date` that pass from the creation of an object and an attribute `data` as an empty dictionary to store data.
- Create one method *add_data* with `t` and `data` as input parameters to take in timestamp and data arrays.
- Within this method, assign `t` and `data` to the `data` attribute with ‘time’ and ‘data’ as the keys.
- In addition, it should have one `clear_data` method to delete the data.

In [ ]:
class Sensor():
    def __init__(self, name, location, record_date):
        self.name = name
        self.location = location
        self.record_date = record_date
        self.data = {}

    def add_data(self, t, data):
        self.data['time'] = t
        self.data['data'] = data
        print(f'We have {len(data)} points saved')

    def clear_data(self):
        self.data = {}
        print('Data cleared!')

- Now we have a class to store general sensor information, we can create a sensor object to store some data.
- **[EXAMPLE]** Create a sensor object.

In [ ]:
import numpy as np

sensor1 = Sensor('sensor1', 'Berkeley', '2019-01-01')
data = np.random.randint(-10, 10, 10)
sensor1.add_data(np.arange(10), data)
sensor1.data

We have 10 points saved

{'time': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'data': array([ 7, -5, -9, -6, -8,  4,  0, -8, -4,  2])}

##### 8.3.1.1. Inherit and Extend New Method

- Say we have one different type of sensor: an accelerometer.
- It **shares the same attributes and methods as `Sensor` class**, but it also has **different attributes or methods need to be appended or modified from the original class**.
- What should we do?
    - Do we create a different class from scratch?
- This is where inheritance can be used to make life easier.
- This new class will inherit from the `Sensor` class with all the attributes and methods.
- We can whether we want to extend the attributes or methods.
- Let us first create this new class, `Accelerometer`, and add a new method, `show_type`, to report what kind of sensor it is.

In [ ]:
class Accelerometer(Sensor):

    def show_type(self):
        print('I am an accelerometer!')

acc = Accelerometer('acc1', 'Oakland', '2019-02-01')
acc.show_type()
data = np.random.randint(-10, 10, 10)
acc.add_data(np.arange(10), data)
acc.data

I am an accelerometer!
We have 10 points saved

{'time': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'data': array([-4,  8, -2,  6,  2, -7,  0, -1,  6, -1])}

- Creating this new `Accelerometer` class is very simple.
- We inherit from `Sensor` (denoted as a superclass), and the new class actually contains all the attributes and methods from the superclass.
- We then add a new method, `show_type`, which does not exist in the `Sensor` class, but we can successfully extend the child class by adding the new method.

- This shows the power of inheritance: we have reused most part of the `Sensor` class in a new class, and extended the functionality.
- Besides, the inheritance sets up a logical relationship for the modeling of the real-world entities:
    - the `Sensor` class as the parent class is more general and passes all the characteristics to the child class `Accelerometer`.

##### 8.3.1.2. Inherit and Method Overriding

- When we inherit from a parent class, we can **change the implementation of a method provided by the parent class**, this is called **method overriding**.
- Let us see the following example.

- **[Example]** Create a class `UCBAcc` (a specific type of accelerometer that created at UC Berkeley) that inherits from `Accelerometer` but replace the `show_type` method that prints out the name of the sensor.

In [ ]:
class UCBAcc(Accelerometer):

    def show_type(self):
        print(f'I am {self.name}, created at UC Berkeley!')

acc_ucb = UCBAcc('UCBAcc', 'Berkeley', '2019-03-01')
acc_ucb.show_type()

I am UCBAcc, created at UC Berkeley!

- We see that, our new `UCBAcc` class actually overrides the method `show_type` with new features.
- In this example, we are not only inheriting features from our parent class, but we are also modifying/improving some methods.

##### 8.3.1.3. Inherit and Update Attributes with `super`

- Let us create a class `NewSensor` that inherits from `Sensor` class, but with updated the attributes by adding a new attribute `brand`.
- Of course, we can re-define the whole `__init__` method as shown below and overriding the parent function.

In [ ]:
class NewSensor(Sensor):
    def __init__(self, name, location, record_date, brand):
        self.name = name
        self.location = location
        self.record_date = record_date
        self.brand = brand
        self.data = {}

new_sensor = NewSensor('OK', 'SF', '2019-03-01', 'XYZ')
new_sensor.brand

'XYZ'

- However, there is a better way to achieve the same.
- We can use the `super` method to avoid referring to the parent class explicitly.
- Let us see how to perform this in the following example:

- **[Example]** Redefine the attributes in inheritance.

In [ ]:
class NewSensor(Sensor):
    def __init__(self, name, location, record_date, brand):
        super().__init__(name, location, record_date)
        self.brand = brand

new_sensor = NewSensor('OK', 'SF', '2019-03-01', 'XYZ')
new_sensor.brand

'XYZ'

- Now we can see with the *super* method, we avoid to list all the definition of the attributes, this **helps keep your code maintainable for the foreseeable future.**
- But it really useful when you are doing multiple inheritance, which is beyond the discussion of this book.

#### 8.3.2. Encapsulation

- **Encapsulation** is one of the fundamental concepts in OOP.
- It describes the idea of **restricting access to methods and attributes in a class**.
- This will hide the complex details from the users, and prevent data being modified by accident.
- In Python, this is achieved by using private methods or attributes using underscore as prefix, i.e. **single “_” or double “__”.**
- Let us see the following example.

- **[Example]**

In [ ]:
class Sensor():
    def __init__(self, name, location):
        self.name = name
        self._location = location
        self.__version = '1.0'

    # a getter function
    def get_version(self):
        print(f'The sensor version is {self.__version}')

    # a setter function
    def set_version(self, version):
        self.__version = version

In [ ]:
sensor1 = Sensor('Acc', 'Berkeley')
print(sensor1.name)
print(sensor1._location)
print(sensor1.__version)

Acc
Berkeley

AttributeError: ignored

- The above example shows how the encapsulation works.
- With single underscore, we defined a private variable, and it should not be accessed directly.
- But this is just convention, nothing stops you from doing that.
    - You can still get access to it if you want to.

- With double underscore, we can see that the attribute `__version` can not be accessed or modify it directly.
- Therefore, to get access to the double underscore attributes, we need to use getter and setter function to access it internally, as shown in the following example.

In [ ]:
sensor1.get_version()

In [ ]:
sensor1.set_version('2.0')
sensor1.get_version()

- The single and double underscore also apply to private methods as well, we will not discuss these as they are similar to the private attributes.

#### 8.3.3. Polymorphism

- **Polymorphism** is another fundamental concept in OOP, which means **multiple forms**.
- Polymorphism allows us to use a single interface with different underlying forms such as data types or classes.
    - For example, we can have commonly named methods across classes or child classes.
- We have already seen one example above, when we override the method `show_type` in the `UCBAcc`.

- For parent class `Accelerometer` and child class `UCBAcc`, they both have a method named `show_type`, but they have different implementation.
- This ability of using single name with many forms acting differently in different situations greatly reduces our complexities.
- We will not expand to discuss more of Polymorphism, if you are interested, check more online to get a deeper understanding.

### **8.4. Building Classes**

- The long, long concept of object-oriented programming is over!
- Since it is difficult to understand at once, let's follow step by step how to configure the class together through examples.

#### 8.4.3. Review on Function

- Consider the polynomial,

$$p(x) = a_0 + a_1 x + a_2 x^2 + a_3 x^3 + \cdots + a_n x^n = \sum_{i=0}^{n} a_i x^i$$

- Write a function `p` such that `p(x, coeff)` that computes the value, given a point `x` and a list of coefficients `coeff`.
- Try to use `enumerate()` in your loop.

In [ ]:
def p(x, coeff):
    return sum(a * x**i for i, a in enumerate(coeff))

p(1, (2, 4)) # p(x) = 2 + 4x

6

- Now, the task is to build a simple class called `Polynomial` for representing and manipulating polynomial functions such as

$$ p(x) = a_0 + a_1 x + a_2 x^2 + a_3 x^3 + \cdots + a_n x^n = \sum_{i=0}^{n} a_i x^i \ \ \ (x \in \mathbb{R}) $$

- The instance data for the class `Polynomial` will be the coefficients.
- Let's provide methods that
    1. Evaluate the polynomial, returning $p(x)$ for any $x$
    2. Differentiate the polynomial, replacing the original coefficients with those of its derivative $p'$.
- Avoid using any import statements.

- First, initiate with `class` statement.

```python
class Polynomial:
```

- Then, define initial values.
    - For example, we need coefficients to calculate values.

```python
class Polynomial:

    def __init__(self, coefficients):
        """
        Creates an instance of the Polynomial class representing

            p(x) = a_0 x^0 + ... + a_N x^N,

        where a_i = coefficients[i].
        """
        self.coefficients = coefficients
```

- Now, given a specific point x, write a function that evaluate the polynomial at x.

```python
class Polynomial:

    def __init__(self, coefficients):
        """
        Creates an instance of the Polynomial class representing

            p(x) = a_0 x^0 + ... + a_N x^N,

        where a_i = coefficients[i].
        """
        self.coefficients = coefficients

    def __call__(self, x):
        "Evaluate the polynomial at x."
        y = 0
        for i, a in enumerate(self.coefficients):
            y += a * x**i
        return y
```

- Finally, write a function that differentiates the given polynomial.

```python
class Polynomial:

    def __init__(self, coefficients):
        """
        Creates an instance of the Polynomial class representing

            p(x) = a_0 x^0 + ... + a_N x^N,

        where a_i = coefficients[i].
        """
        self.coefficients = coefficients

    def __call__(self, x):
        "Evaluate the polynomial at x."
        y = 0
        for i, a in enumerate(self.coefficients):
            y += a * x**i
        return y

    def differentiate(self):
        "Reset self.coefficients to those of p' instead of p."
        new_coefficients = []
        for i, a in enumerate(self.coefficients):
            new_coefficients.append(i * a)
        # Remove the first element, which is zero
        del new_coefficients[0]
        # And reset coefficients data to new values
        self.coefficients = new_coefficients
        return new_coefficients
```

---

- 드디어 첫주차 학습 노트가 끝났습니다!
- 양이 많고 생소한 개념이 있어 힘드셨을텐데 모두 수고하셨습니다!
- 학습자료를 만들면서도 느꼈지만 오늘이 가장 힘들 수 있는 한 주라고 생각됩니다.
- 매주 이러진 않을테니 우리 모두 힘내서 앞으로 16주간 파이팅하면 좋겠습니다!👻

## **A. References**

- [1] Introduction to economic modeling and data science. (n.d.). QuantEcon DataScience. Retrieved July 26, 2023, from https://datascience.quantecon.org/
- [2] Kong, Q., Siauw, T., & Bayen, A. (2020). Python programming and numerical methods: A guide for engineers and scientists. Academic Press.
- [3] Lin, S. Y. T., & Lin, Y. F. (1974). Set theory an intuitive approach.